INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('﻿category', 'calories');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Soft Corn Tortillas for Kid's Taco', '70');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Fajita Vegetables', '6');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Crispy Corn Tortillas for Kid's Taco', '70');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Soft Flour Tortilla for Kid's Small Quesadilla or Taco', '85');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Cheese', '30');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Tomatillo-Green Chili Salsa', '7');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Romaine Lettuce for Taco or Burrito', '3');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Soft Flour Tortillas for Tacos', '255');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Soft Flour Tortilla for Burrito', '300');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Filling, Sofritas', '47');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Brown Rice', '125');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Filling, Chicken', '59');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Vinaigrette', '215');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Crispy Corn Tortillas', '210');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Chips, without salsa', '143');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Tomatillo-Red Chili Salsa', '9');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Romaine Lettuce for Salad', '10');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Guacamole', '58');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Filling, Barbacoa', '54');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Sour Cream', '40');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Black Beans', '39');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Filling, Steak', '62');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Pinto Beans', '38');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Soft Corn Tortillas', '210');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Roasted Chili-Corn Salsa', '27');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Filling, Carnitas', '72');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('Fresh Tomato Salsa', '7');
INSERT INTO `hwangmn`.`chipotle` (`food`, `calories`) VALUES ('White Rice', '116');
