insert into fooduser (Email, Food) values ('mburns0@hc360.com', 'Doxycycline Hyclate');
insert into fooduser (Email, Food) values ('vgomez1@imdb.com', 'Banana Boat Sport Performance SPF 85');
insert into fooduser (Email, Food) values ('fharris2@hc360.com', 'Losartan Potassium and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('jowens3@blogspot.com', 'HYDROXYZINE HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('sellis4@usa.gov', 'LISINOPRIL');
insert into fooduser (Email, Food) values ('egarrett5@discovery.com', 'Erborian BB Creme Au Ginseng');
insert into fooduser (Email, Food) values ('scrawford6@virginia.edu', 'Tummy Aches and Gas');
insert into fooduser (Email, Food) values ('crose7@cnn.com', 'ATOMY SUNSCREEN');
insert into fooduser (Email, Food) values ('mbutler8@paginegialle.it', 'Ibuprofen');
insert into fooduser (Email, Food) values ('aramirez9@oaic.gov.au', 'Treatment Set TS331327');
insert into fooduser (Email, Food) values ('apetersona@yahoo.co.jp', 'fluvoxamine maleate');
insert into fooduser (Email, Food) values ('jrobinsonb@myspace.com', 'Bromfenac');
insert into fooduser (Email, Food) values ('apiercec@g.co', 'Cyclobenzaprine Hydrochloride');
insert into fooduser (Email, Food) values ('ndiazd@weather.com', 'Gabapentin');
insert into fooduser (Email, Food) values ('aburnse@cargocollective.com', 'Maximum Strength Flu BP');
insert into fooduser (Email, Food) values ('jricef@house.gov', 'ESIKA');
insert into fooduser (Email, Food) values ('mmoralesg@e-recht24.de', 'Nifedipine');
insert into fooduser (Email, Food) values ('jfergusonh@cbslocal.com', 'Divalproex Sodium');
insert into fooduser (Email, Food) values ('amorrisi@usda.gov', 'Progesterone');
insert into fooduser (Email, Food) values ('jvasquezj@unesco.org', 'SOLAR SENSE CLEAR ZINC SUNSCREEN VALUE PACK 50 PLUS');
insert into fooduser (Email, Food) values ('clynchk@php.net', 'SOFT AND PRECIOUS NURSERY');
insert into fooduser (Email, Food) values ('gfranklinl@dropbox.com', 'Chlorpromazine Hydrochloride');
insert into fooduser (Email, Food) values ('jsimpsonm@webnode.com', 'Betamethasone Valerate');
insert into fooduser (Email, Food) values ('sellisn@bing.com', 'Methylphenidate Hydrochloride');
insert into fooduser (Email, Food) values ('dbrookso@dmoz.org', 'Simvastatin');
insert into fooduser (Email, Food) values ('hgarzap@netscape.com', 'Oxygen');
insert into fooduser (Email, Food) values ('gjacobsq@i2i.jp', 'Spinach');
insert into fooduser (Email, Food) values ('rgarciar@sakura.ne.jp', 'Renaforce');
insert into fooduser (Email, Food) values ('jjacobss@webnode.com', 'Allopurinol');
insert into fooduser (Email, Food) values ('rellist@state.gov', 'Escavite D');
insert into fooduser (Email, Food) values ('jmurphyu@harvard.edu', 'germstarNORO');
insert into fooduser (Email, Food) values ('rhunterv@xing.com', 'Equate nicotine');
insert into fooduser (Email, Food) values ('cjonesw@intel.com', 'Mexican Tea Pollen');
insert into fooduser (Email, Food) values ('thughesx@mozilla.com', 'Head and Shoulders');
insert into fooduser (Email, Food) values ('jmorgany@123-reg.co.uk', 'ZIAGEN');
insert into fooduser (Email, Food) values ('ppaynez@vistaprint.com', 'Iris germanica comp.');
insert into fooduser (Email, Food) values ('drose10@taobao.com', 'Proparacaine Hydrochloride');
insert into fooduser (Email, Food) values ('wrussell11@comcast.net', 'NIN JIOM PEI PA KOA');
insert into fooduser (Email, Food) values ('lshaw12@indiatimes.com', 'Covergirl Outlast Stay Fabulous 3in1 Foundation');
insert into fooduser (Email, Food) values ('sroberts13@godaddy.com', 'Oxcarbazepine');
insert into fooduser (Email, Food) values ('greynolds14@miibeian.gov.cn', 'Analpram E');
insert into fooduser (Email, Food) values ('dcarr15@ning.com', 'Colgate Sensitive Multiprotection');
insert into fooduser (Email, Food) values ('jcooper16@yelp.com', 'ITCHY SKIN RUNNY NOSE');
insert into fooduser (Email, Food) values ('brice17@utexas.edu', 'Maalox Antacid');
insert into fooduser (Email, Food) values ('ngreen18@spotify.com', 'Nystatin');
insert into fooduser (Email, Food) values ('mfoster19@webnode.com', 'Nitrostat');
insert into fooduser (Email, Food) values ('ngonzales1a@va.gov', 'nifedipine');
insert into fooduser (Email, Food) values ('pwebb1b@un.org', 'Potassium Chloride in Dextrose and Sodium Chloride');
insert into fooduser (Email, Food) values ('dwallace1c@1und1.de', 'Stratuscare Glycerin Laxative Pediatric');
insert into fooduser (Email, Food) values ('jlarson1d@salon.com', 'WELLBUTRIN');
insert into fooduser (Email, Food) values ('fkennedy1e@phoca.cz', 'ACNE SOLUTIONS CLARIFYING');
insert into fooduser (Email, Food) values ('srichards1f@usda.gov', 'SOLIDAGO CANADENSIS POLLEN');
insert into fooduser (Email, Food) values ('jwhite1g@unesco.org', 'Piperacillin, Tazobactam');
insert into fooduser (Email, Food) values ('mtaylor1h@cmu.edu', 'Nephroplex');
insert into fooduser (Email, Food) values ('golson1i@friendfeed.com', 'Furosemide');
insert into fooduser (Email, Food) values ('wcoleman1j@about.me', 'La Roche Posay Redermic C UV Sunscreen');
insert into fooduser (Email, Food) values ('ahughes1k@cloudflare.com', 'VENLAFAXINE HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('nrichardson1l@accuweather.com', 'Topcare Sinus Congestion and Pain');
insert into fooduser (Email, Food) values ('ajordan1m@nymag.com', 'Ibuprofen');
insert into fooduser (Email, Food) values ('bwest1n@bbc.co.uk', 'elimite');
insert into fooduser (Email, Food) values ('lalvarez1o@icio.us', 'Chocolated Laxative');
insert into fooduser (Email, Food) values ('gfields1p@ted.com', 'Canadian Blue Grass');
insert into fooduser (Email, Food) values ('phawkins1q@diigo.com', 'Hand Sanitizer');
insert into fooduser (Email, Food) values ('dsullivan1r@1688.com', 'Sun Shades');
insert into fooduser (Email, Food) values ('jhanson1s@google.com.hk', 'Panache');
insert into fooduser (Email, Food) values ('fcampbell1t@meetup.com', 'miconazole 1');
insert into fooduser (Email, Food) values ('mflores1u@businesswire.com', 'Mucinex Fast-Max');
insert into fooduser (Email, Food) values ('gmyers1v@taobao.com', 'Lidocaine Hydrochloride');
insert into fooduser (Email, Food) values ('amorrison1w@dagondesign.com', 'Venlafaxine Hydrochloride');
insert into fooduser (Email, Food) values ('hhall1x@arstechnica.com', 'Medrol');
insert into fooduser (Email, Food) values ('bferguson1y@dot.gov', 'DR. RECKEWEG R68 Herpezostin');
insert into fooduser (Email, Food) values ('dowens1z@1und1.de', 'Benztropine Mesylate');
insert into fooduser (Email, Food) values ('kbutler20@nbcnews.com', 'Trazodone Hydrochloride');
insert into fooduser (Email, Food) values ('kwallace21@gov.uk', 'Hops');
insert into fooduser (Email, Food) values ('bclark22@google.de', 'bethanechol chloride');
insert into fooduser (Email, Food) values ('lmitchell23@barnesandnoble.com', 'Midazolam Hydrochloride');
insert into fooduser (Email, Food) values ('jjordan24@friendfeed.com', 'Neomycin and Polymyxin B Sulfates, Bacitracin Zinc and Hydrocortisone');
insert into fooduser (Email, Food) values ('jgibson25@e-recht24.de', 'Allscale');
insert into fooduser (Email, Food) values ('pdunn26@i2i.jp', 'Sisal');
insert into fooduser (Email, Food) values ('abarnes27@theatlantic.com', 'P32 Sodium Phosphate');
insert into fooduser (Email, Food) values ('bwelch28@eepurl.com', 'ANTIVENIN');
insert into fooduser (Email, Food) values ('breynolds29@gizmodo.com', 'In Control Nicotine');
insert into fooduser (Email, Food) values ('jrice2a@hibu.com', 'HEMETAB');
insert into fooduser (Email, Food) values ('cblack2b@hhs.gov', 'Allergy');
insert into fooduser (Email, Food) values ('golson2c@infoseek.co.jp', 'Heparin Sodium');
insert into fooduser (Email, Food) values ('awagner2d@ftc.gov', 'Isopropyl Alcohol');
insert into fooduser (Email, Food) values ('jfields2e@symantec.com', 'Walgreens Muscle Rub');
insert into fooduser (Email, Food) values ('rgarza2f@wp.com', 'LBEL Couleur Luxe Rouge Amplifier XP amplifying SPF 15');
insert into fooduser (Email, Food) values ('dcunningham2g@fda.gov', 'Neocidin');
insert into fooduser (Email, Food) values ('hscott2h@cbc.ca', 'Secura Personal Cleanser');
insert into fooduser (Email, Food) values ('acarpenter2i@buzzfeed.com', 'Neostigmine Methylsulfate');
insert into fooduser (Email, Food) values ('hgilbert2j@dot.gov', 'Amlodipine Besylate');
insert into fooduser (Email, Food) values ('jrichards2k@mozilla.org', 'Furosemide');
insert into fooduser (Email, Food) values ('rward2l@wikispaces.com', 'Breast Help');
insert into fooduser (Email, Food) values ('jhenry2m@live.com', 'Ciprofloxacin');
insert into fooduser (Email, Food) values ('rfields2n@over-blog.com', 'Redtop Grass, Standardized');
insert into fooduser (Email, Food) values ('kwebb2o@smugmug.com', 'DIGOX');
insert into fooduser (Email, Food) values ('abarnes2p@woothemes.com', 'Diazepam');
insert into fooduser (Email, Food) values ('rjones2q@google.com.br', 'Venlafaxine');
insert into fooduser (Email, Food) values ('jbaker2r@nyu.edu', 'Hydromorphone Hydrochloride');
insert into fooduser (Email, Food) values ('sdunn2s@howstuffworks.com', 'Temazepam');
insert into fooduser (Email, Food) values ('psmith2t@mapquest.com', 'Sani Professional Brand Sani-Hands with Tencel');
insert into fooduser (Email, Food) values ('fcook2u@rambler.ru', 'Taclonex');
insert into fooduser (Email, Food) values ('jrichardson2v@skype.com', 'isosorbide mononitrate');
insert into fooduser (Email, Food) values ('rsims2w@posterous.com', 'ONDANSETRON HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('kriley2x@pbs.org', 'Warfarin Sodium');
insert into fooduser (Email, Food) values ('dtaylor2y@over-blog.com', 'Finafta');
insert into fooduser (Email, Food) values ('ajones2z@loc.gov', 'Cold and Allergy');
insert into fooduser (Email, Food) values ('lschmidt30@tmall.com', 'Fluvoxamine Maleate');
insert into fooduser (Email, Food) values ('agutierrez31@typepad.com', 'Olanzapine');
insert into fooduser (Email, Food) values ('jcunningham32@census.gov', 'UNDECYLENIC ACID');
insert into fooduser (Email, Food) values ('tfuller33@irs.gov', 'Good Sense Triple Antibiotic');
insert into fooduser (Email, Food) values ('sdavis34@slideshare.net', 'Montelukast Sodium');
insert into fooduser (Email, Food) values ('afox35@livejournal.com', 'acetaminophen');
insert into fooduser (Email, Food) values ('rhowell36@histats.com', 'Morning Sickness');
insert into fooduser (Email, Food) values ('jvasquez37@bloglines.com', 'Eight Hour Cream Skin Protectant');
insert into fooduser (Email, Food) values ('smartinez38@apache.org', 'West Cottonwood');
insert into fooduser (Email, Food) values ('dprice39@mapquest.com', 'Ofirmev');
insert into fooduser (Email, Food) values ('treed3a@blogger.com', 'Lyrica');
insert into fooduser (Email, Food) values ('wwheeler3b@tripod.com', 'miconazole 1');
insert into fooduser (Email, Food) values ('bburton3c@so-net.ne.jp', 'Doxycycline');
insert into fooduser (Email, Food) values ('nmason3d@howstuffworks.com', 'LEVAQUIN');
insert into fooduser (Email, Food) values ('rturner3e@telegraph.co.uk', 'levalbuterol inhalation');
insert into fooduser (Email, Food) values ('sward3f@facebook.com', 'TEMODAR');
insert into fooduser (Email, Food) values ('rcruz3g@xing.com', 'Lucky Antibacterial Hand Soap');
insert into fooduser (Email, Food) values ('mturner3h@bravesites.com', 'Triamcinolone Acetonide');
insert into fooduser (Email, Food) values ('canderson3i@blog.com', 'XANTHIUM STRUMARIUM VAR CANADENSE POLLEN');
insert into fooduser (Email, Food) values ('bhansen3j@hostgator.com', 'Broncotron');
insert into fooduser (Email, Food) values ('scruz3k@mail.ru', 'Sulwhasoo Lumitouch');
insert into fooduser (Email, Food) values ('aellis3l@e-recht24.de', 'Haloperidol');
insert into fooduser (Email, Food) values ('pnelson3m@shareasale.com', 'good sense jock itch');
insert into fooduser (Email, Food) values ('jboyd3n@tiny.cc', 'Donepezil Hydrochloride');
insert into fooduser (Email, Food) values ('dfox3o@dropbox.com', 'HYDROCORTISONE');
insert into fooduser (Email, Food) values ('lmyers3p@comsenz.com', 'Magnacet');
insert into fooduser (Email, Food) values ('jkim3q@comcast.net', 'Ranitidine');
insert into fooduser (Email, Food) values ('rcoleman3r@xing.com', 'ALA-HIST PE');
insert into fooduser (Email, Food) values ('sward3s@xrea.com', 'Duloxetine');
insert into fooduser (Email, Food) values ('mchapman3t@fastcompany.com', 'PhysiciansCare Ophthalmic Solution Eyewash');
insert into fooduser (Email, Food) values ('jcarpenter3u@cdc.gov', 'Mysoline');
insert into fooduser (Email, Food) values ('lperkins3v@goodreads.com', 'Ultra Nutrition Eye');
insert into fooduser (Email, Food) values ('astanley3w@pen.io', 'Clonazepam');
insert into fooduser (Email, Food) values ('srobertson3x@technorati.com', 'Lithium Carbonate');
insert into fooduser (Email, Food) values ('dfoster3y@rakuten.co.jp', 'Bambusa Viscum Stannum');
insert into fooduser (Email, Food) values ('sjordan3z@archive.org', 'Ropinirole Hydrochloride');
insert into fooduser (Email, Food) values ('ashaw40@narod.ru', 'Hand Sanitizer');
insert into fooduser (Email, Food) values ('dsanchez41@answers.com', 'GLIPIZIDE');
insert into fooduser (Email, Food) values ('dhart42@friendfeed.com', 'Dextroamphetamine saccharate, amphetamine aspartate monohydrate, dextroamphetamine sulfate and amphetamine sulfate');
insert into fooduser (Email, Food) values ('mrobinson43@baidu.com', 'Fluconazole');
insert into fooduser (Email, Food) values ('amcdonald44@trellian.com', 'Temazepam');
insert into fooduser (Email, Food) values ('sgrant45@yale.edu', 'Motrin IB');
insert into fooduser (Email, Food) values ('tlittle46@un.org', 'Carbidopa and levodopa');
insert into fooduser (Email, Food) values ('klopez47@tinypic.com', 'Amlodipine Besylate');
insert into fooduser (Email, Food) values ('agibson48@friendfeed.com', 'healthy accents nasal');
insert into fooduser (Email, Food) values ('iprice49@reuters.com', 'Prednisolone Sodium Phosphate');
insert into fooduser (Email, Food) values ('rferguson4a@livejournal.com', 'Oxycodone and Acetaminophen');
insert into fooduser (Email, Food) values ('jsmith4b@spotify.com', 'Assured Alcohol Cleansing Pad');
insert into fooduser (Email, Food) values ('ghoward4c@columbia.edu', 'Torisel');
insert into fooduser (Email, Food) values ('bevans4d@unblog.fr', 'Seborrheic');
insert into fooduser (Email, Food) values ('jlee4e@mozilla.org', 'Purmist');
insert into fooduser (Email, Food) values ('tmedina4f@go.com', 'leader acid reducer');
insert into fooduser (Email, Food) values ('jwillis4g@about.com', 'Verapamil Hydrochloride');
insert into fooduser (Email, Food) values ('amoreno4h@umn.edu', 'Hydrocodone Bitartrate And Acetaminophen');
insert into fooduser (Email, Food) values ('kpowell4i@imgur.com', 'MEGA-C-ACID');
insert into fooduser (Email, Food) values ('rmcdonald4j@chron.com', 'PAROXETINE');
insert into fooduser (Email, Food) values ('scrawford4k@studiopress.com', 'Muscle Rub Ultra');
insert into fooduser (Email, Food) values ('bcunningham4l@fema.gov', 'Helium');
insert into fooduser (Email, Food) values ('rreynolds4m@usgs.gov', 'Back, Neck, Muscle, and Joint Injuries Relief');
insert into fooduser (Email, Food) values ('gford4n@pcworld.com', 'Aquaphor');
insert into fooduser (Email, Food) values ('randerson4o@com.com', 'Allergy');
insert into fooduser (Email, Food) values ('jlewis4p@springer.com', 'Ondansetron Hydrochloride');
insert into fooduser (Email, Food) values ('cward4q@va.gov', 'SEROQUEL');
insert into fooduser (Email, Food) values ('lwebb4r@ask.com', 'CAMPHOR');
insert into fooduser (Email, Food) values ('barmstrong4s@cbc.ca', 'Hannaford Hand Sanitizer');
insert into fooduser (Email, Food) values ('amyers4t@wordpress.org', 'Gehwol med Foot');
insert into fooduser (Email, Food) values ('bjohnson4u@imageshack.us', 'Prep Solution');
insert into fooduser (Email, Food) values ('astevens4v@jalbum.net', 'Mucinex');
insert into fooduser (Email, Food) values ('tgilbert4w@usgs.gov', 'Head and Shoulders');
insert into fooduser (Email, Food) values ('clane4x@edublogs.org', 'Pollens - Trees, Mesquite, Prosopis juliflora');
insert into fooduser (Email, Food) values ('lpatterson4y@mapquest.com', 'Contac Cold and Flu');
insert into fooduser (Email, Food) values ('mperry4z@stumbleupon.com', 'Brompheniramine Pseudoephedrine DM');
insert into fooduser (Email, Food) values ('pbishop50@ucla.edu', 'AMITRIPTYLINE HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('swatson51@mysql.com', 'HGH Vitality');
insert into fooduser (Email, Food) values ('rallen52@springer.com', 'Lopressor');
insert into fooduser (Email, Food) values ('eross53@chron.com', 'Hydralazine Hydrochloride');
insert into fooduser (Email, Food) values ('areyes54@meetup.com', 'Bumetanide');
insert into fooduser (Email, Food) values ('psanchez55@scribd.com', 'ESIKA HYDRACOLOR 2 IN 1 HIGHLY MOISTURIZING AND COLORING SPF 25');
insert into fooduser (Email, Food) values ('promero56@globo.com', 'Losartan Potassium and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('pmorrison57@webs.com', 'Synthroid');
insert into fooduser (Email, Food) values ('bgarcia58@java.com', 'Atenolol');
insert into fooduser (Email, Food) values ('csimmons59@cdbaby.com', 'Thyme');
insert into fooduser (Email, Food) values ('abowman5a@amazon.com', 'Tineacide Physician Formula');
insert into fooduser (Email, Food) values ('rross5b@cbc.ca', 'nitetime');
insert into fooduser (Email, Food) values ('bblack5c@chicagotribune.com', 'Eight Hour Cream Intensive Daily Moisturizer For Face SPF 15');
insert into fooduser (Email, Food) values ('dgilbert5d@macromedia.com', 'YES TO TOMATOES ROLLER BALL SPOT STICK');
insert into fooduser (Email, Food) values ('grodriguez5e@google.co.uk', 'Lisinopril with Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('dlynch5f@google.com.au', 'Neutrogena Revitalizing Lip Balm');
insert into fooduser (Email, Food) values ('mwilson5g@jiathis.com', 'REFISSA');
insert into fooduser (Email, Food) values ('hevans5h@sakura.ne.jp', 'Lidocaine Hydrochloride');
insert into fooduser (Email, Food) values ('jwarren5i@123-reg.co.uk', 'Idamycin PFS');
insert into fooduser (Email, Food) values ('lriley5j@noaa.gov', 'Nicotine');
insert into fooduser (Email, Food) values ('rpowell5k@wix.com', 'NITROGEN');
insert into fooduser (Email, Food) values ('asanders5l@msu.edu', 'Pramipexole Dihydrochloride');
insert into fooduser (Email, Food) values ('kbutler5m@unesco.org', 'Gliadel');
insert into fooduser (Email, Food) values ('jhowell5n@goo.gl', 'Naturals Pomegranate and Mango');
insert into fooduser (Email, Food) values ('mparker5o@freewebs.com', 'leader tussin dm');
insert into fooduser (Email, Food) values ('rrodriguez5p@ebay.co.uk', 'Triamcinolone Acetonide');
insert into fooduser (Email, Food) values ('gcrawford5q@macromedia.com', 'Equaline tussin cough and chest congestion');
insert into fooduser (Email, Food) values ('saustin5r@google.pl', 'Ibuprofen');
insert into fooduser (Email, Food) values ('dsnyder5s@army.mil', '4Life Enummi Protective Day Moisturizer');
insert into fooduser (Email, Food) values ('ghoward5t@vimeo.com', 'Sulfamethoxazole and Trimethoprim');
insert into fooduser (Email, Food) values ('nlewis5u@multiply.com', 'Tramadol Hydrochloride');
insert into fooduser (Email, Food) values ('rcarter5v@gmpg.org', 'SunZone Sunscreen Family SPF 30');
insert into fooduser (Email, Food) values ('cyoung5w@blogs.com', 'Azithromycin');
insert into fooduser (Email, Food) values ('hgonzales5x@nba.com', 'Citalopram Hydrobromide');
insert into fooduser (Email, Food) values ('ajordan5y@ted.com', 'Venlafaxine Hydrochloride');
insert into fooduser (Email, Food) values ('tgardner5z@twitter.com', 'Trazodone Hydrochloride');
insert into fooduser (Email, Food) values ('jfuller60@eepurl.com', 'Spironolactone and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('jford61@merriam-webster.com', 'Primidone');
insert into fooduser (Email, Food) values ('kromero62@jimdo.com', 'Wal-Dryl');
insert into fooduser (Email, Food) values ('rcooper63@prnewswire.com', 'Propranolol Hydrochloride');
insert into fooduser (Email, Food) values ('jalexander64@bbb.org', 'Divalproex SodiumDelayed-Release');
insert into fooduser (Email, Food) values ('jburke65@cnn.com', 'Cyclomydril');
insert into fooduser (Email, Food) values ('rwilson66@ca.gov', 'ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)');
insert into fooduser (Email, Food) values ('ndiaz67@discuz.net', 'Tinted Moisturizer SPF20');
insert into fooduser (Email, Food) values ('jjordan68@linkedin.com', 'ALTABAX');
insert into fooduser (Email, Food) values ('rbanks69@upenn.edu', 'Rough Pigweed');
insert into fooduser (Email, Food) values ('kstephens6a@360.cn', 'Atenolol');
insert into fooduser (Email, Food) values ('cpalmer6b@macromedia.com', 'Beauty Counter Protect All over Sunscreen');
insert into fooduser (Email, Food) values ('jcook6c@tinypic.com', 'Rifamate');
insert into fooduser (Email, Food) values ('mcruz6d@mysql.com', 'Saltbush');
insert into fooduser (Email, Food) values ('pfisher6e@nymag.com', 'Ibuprofen');
insert into fooduser (Email, Food) values ('tsimpson6f@flickr.com', 'alcohol');
insert into fooduser (Email, Food) values ('rramos6g@amazon.co.jp', 'Tacrolimus');
insert into fooduser (Email, Food) values ('bduncan6h@cmu.edu', 'COUMADIN');
insert into fooduser (Email, Food) values ('gfranklin6i@opensource.org', 'Quietude');
insert into fooduser (Email, Food) values ('mross6j@intel.com', 'Risperidone');
insert into fooduser (Email, Food) values ('sray6k@ebay.co.uk', 'Covergirl Queen Collection All Day Flawless 3in1 Foundation');
insert into fooduser (Email, Food) values ('wsullivan6l@cnet.com', 'Dakins Half');
insert into fooduser (Email, Food) values ('mduncan6m@youtu.be', 'Panama Jack');
insert into fooduser (Email, Food) values ('ssims6n@ftc.gov', 'Ibuprofen');
insert into fooduser (Email, Food) values ('tjohnston6o@blogger.com', 'Gabapentin');
insert into fooduser (Email, Food) values ('agordon6p@github.com', 'Divigel');
insert into fooduser (Email, Food) values ('apeters6q@unicef.org', 'good sense nasal');
insert into fooduser (Email, Food) values ('waustin6r@nymag.com', 'ARRID XX Extra Extra Dry Invisible Solid');
insert into fooduser (Email, Food) values ('bramirez6s@hhs.gov', 'Sanafitil Talco');
insert into fooduser (Email, Food) values ('jberry6t@indiatimes.com', 'Haloperidol');
insert into fooduser (Email, Food) values ('lsimpson6u@umich.edu', 'Ice Quake');
insert into fooduser (Email, Food) values ('ccollins6v@t-online.de', 'Methotrexate');
insert into fooduser (Email, Food) values ('mvasquez6w@indiatimes.com', 'MINOCYCLINE HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('bsimmons6x@parallels.com', 'simple pleasures');
insert into fooduser (Email, Food) values ('smendoza6y@independent.co.uk', 'Traumeel');
insert into fooduser (Email, Food) values ('kcook6z@free.fr', 'Salsalate');
insert into fooduser (Email, Food) values ('lpeterson70@imageshack.us', 'Fluoxetine');
insert into fooduser (Email, Food) values ('nmorrison71@sogou.com', 'Metformin Hydrochloride');
insert into fooduser (Email, Food) values ('wdixon72@reuters.com', 'Salonpas DEEP Relieving');
insert into fooduser (Email, Food) values ('cbrown73@icio.us', 'Childrens Allergy');
insert into fooduser (Email, Food) values ('aknight74@prlog.org', 'Warfarin Sodium');
insert into fooduser (Email, Food) values ('bmitchell75@google.com.au', 'HOG HAIR AND EPITHELIA');
insert into fooduser (Email, Food) values ('dlewis76@ted.com', 'Cold Head Congestion');
insert into fooduser (Email, Food) values ('dsmith77@google.nl', 'Topcare ibuprofen');
insert into fooduser (Email, Food) values ('cfernandez78@ucoz.com', 'Tomato Day Broad Spectrum SPF 16 Sunscreen');
insert into fooduser (Email, Food) values ('dmorrison79@twitter.com', 'Lidocaine and Prilocaine');
insert into fooduser (Email, Food) values ('jturner7a@gnu.org', 'Egotistical');
insert into fooduser (Email, Food) values ('dcollins7b@dell.com', 'ADVANCED HYDRO-LIQUID COMPACT (REFILL)');
insert into fooduser (Email, Food) values ('thart7c@ocn.ne.jp', 'Mandarin Orange Antibacterial Foaming Hand Wash');
insert into fooduser (Email, Food) values ('jcrawford7d@nymag.com', 'Heparin Sodium');
insert into fooduser (Email, Food) values ('jedwards7e@geocities.jp', 'Sweet Candy Kiss Sanitizer Pen');
insert into fooduser (Email, Food) values ('jfisher7f@over-blog.com', 'rx act pain relief');
insert into fooduser (Email, Food) values ('jlittle7g@ycombinator.com', 'ORIGINAL POWER WHITENING AND LINELESS AMPOULE');
insert into fooduser (Email, Food) values ('kharris7h@gmpg.org', 'Mucinex');
insert into fooduser (Email, Food) values ('msanders7i@behance.net', 'Headache');
insert into fooduser (Email, Food) values ('bcampbell7j@moonfruit.com', 'good sense nighttime sleep aid');
insert into fooduser (Email, Food) values ('aflores7k@sina.com.cn', 'Scape SPF 50 Moisturizing Face');
insert into fooduser (Email, Food) values ('rmurray7l@toplist.cz', 'AQUAFRESH');
insert into fooduser (Email, Food) values ('jdunn7m@webs.com', 'Baclofen');
insert into fooduser (Email, Food) values ('rwebb7n@blogtalkradio.com', 'Antacid');
insert into fooduser (Email, Food) values ('baustin7o@chicagotribune.com', 'Coralite Extra Strength Menthol Pain Relief Sleeve - KNEE');
insert into fooduser (Email, Food) values ('mmurphy7p@hatena.ne.jp', 'Lamotrigine');
insert into fooduser (Email, Food) values ('lrobertson7q@seesaa.net', 'Omeprazole');
insert into fooduser (Email, Food) values ('rhenderson7r@mlb.com', 'Hydroxyzine Hydrochloride');
insert into fooduser (Email, Food) values ('kmatthews7s@seesaa.net', 'CELL BOOSTING BB');
insert into fooduser (Email, Food) values ('dfox7t@godaddy.com', 'Paclitaxel');
insert into fooduser (Email, Food) values ('whawkins7u@wiley.com', 'Fluconazole');
insert into fooduser (Email, Food) values ('cjames7v@squidoo.com', 'Nifedipine');
insert into fooduser (Email, Food) values ('mmorrison7w@zimbio.com', 'TUMS');
insert into fooduser (Email, Food) values ('rrivera7x@dell.com', 'Meloxicam');
insert into fooduser (Email, Food) values ('lmccoy7y@seattletimes.com', 'IQQU Advance Sunscreen');
insert into fooduser (Email, Food) values ('jyoung7z@dailymail.co.uk', 'ZALEPLON');
insert into fooduser (Email, Food) values ('dhill80@netscape.com', 'meperidine hydrochloride');
insert into fooduser (Email, Food) values ('lcrawford81@boston.com', 'Nisoldipine');
insert into fooduser (Email, Food) values ('jrobinson82@google.co.uk', 'Hydroxyzine Hydrochloride');
insert into fooduser (Email, Food) values ('btucker83@is.gd', 'Gold Bond Ultimate Hand Sanitizer Moisturizer');
insert into fooduser (Email, Food) values ('srodriguez84@nydailynews.com', 'AsthmaClear');
insert into fooduser (Email, Food) values ('pgray85@lulu.com', 'Hydralazine Hydrochloride');
insert into fooduser (Email, Food) values ('cjames86@pcworld.com', 'Pollens - Trees, Mesquite, Prosopis juliflora');
insert into fooduser (Email, Food) values ('adunn87@tiny.cc', 'Advanced Healing');
insert into fooduser (Email, Food) values ('rthomas88@sina.com.cn', 'Aztreonam');
insert into fooduser (Email, Food) values ('tgonzalez89@netlog.com', 'Protonix');
insert into fooduser (Email, Food) values ('fnelson8a@netscape.com', 'Renew');
insert into fooduser (Email, Food) values ('afox8b@taobao.com', 'SohMed Pain Reliever');
insert into fooduser (Email, Food) values ('vwallace8c@bloglovin.com', 'Cepacol');
insert into fooduser (Email, Food) values ('jlong8d@livejournal.com', 'Paroxetine');
insert into fooduser (Email, Food) values ('jellis8e@uol.com.br', 'Dove Men plus Care');
insert into fooduser (Email, Food) values ('eturner8f@gnu.org', 'BOLDO');
insert into fooduser (Email, Food) values ('jcarr8g@time.com', 'Childrens Mapap');
insert into fooduser (Email, Food) values ('garmstrong8h@jalbum.net', 'Fabior');
insert into fooduser (Email, Food) values ('telliott8i@lulu.com', 'Losartan Potassium');
insert into fooduser (Email, Food) values ('rsims8j@zimbio.com', 'Neomycin and Polymyxin B Sulfates and Bacitracin Zinc with Hydrocortisone Acetate');
insert into fooduser (Email, Food) values ('lferguson8k@prnewswire.com', 'METFORMIN HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('awatkins8l@hao123.com', 'ASPIRIN LOW DOSE');
insert into fooduser (Email, Food) values ('choward8m@psu.edu', 'Quetiapine fumarate');
insert into fooduser (Email, Food) values ('jhamilton8n@google.co.uk', 'SIMPLY RIGHT BODY CARE');
insert into fooduser (Email, Food) values ('gwilliamson8o@chron.com', 'omeprazole');
insert into fooduser (Email, Food) values ('lweaver8p@linkedin.com', 'AMOXICILLIN');
insert into fooduser (Email, Food) values ('tford8q@independent.co.uk', 'Aveeno Soothing Bath Treatment');
insert into fooduser (Email, Food) values ('pjordan8r@bing.com', 'ZONISAMIDE');
insert into fooduser (Email, Food) values ('rmorris8s@fotki.com', 'Old Spice Red Zone Sweat Defense');
insert into fooduser (Email, Food) values ('spatterson8t@scribd.com', 'Krystexxa');
insert into fooduser (Email, Food) values ('eryan8u@globo.com', 'TRUFFLE EX CLEANSING');
insert into fooduser (Email, Food) values ('afoster8v@technorati.com', 'Sleep Aid');
insert into fooduser (Email, Food) values ('trose8w@yandex.ru', 'Dextrose');
insert into fooduser (Email, Food) values ('rcruz8x@wufoo.com', 'Quinapril Hydrochloride and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('jthompson8y@skype.com', 'Atopalm Maximum Strength Anti-Itch');
insert into fooduser (Email, Food) values ('hgilbert8z@woothemes.com', 'Atorvastatin Calcium');
insert into fooduser (Email, Food) values ('ccarr90@goo.gl', 'Temovate');
insert into fooduser (Email, Food) values ('ckim91@opera.com', 'Pleo Rub');
insert into fooduser (Email, Food) values ('kshaw92@cbc.ca', 'Trandolapril');
insert into fooduser (Email, Food) values ('agarza93@washingtonpost.com', 'Ery-Ped');
insert into fooduser (Email, Food) values ('clarson94@ycombinator.com', 'HEMORRHOIDS PROCTALGIA');
insert into fooduser (Email, Food) values ('jchavez95@pbs.org', 'Oxygen, Compressed');
insert into fooduser (Email, Food) values ('skim96@mit.edu', 'Atomoxetine hydrochloride');
insert into fooduser (Email, Food) values ('arose97@cbslocal.com', 'help me');
insert into fooduser (Email, Food) values ('dsullivan98@nbcnews.com', 'Isosorbide Dinitrate');
insert into fooduser (Email, Food) values ('agibson99@whitehouse.gov', 'REQUIP');
insert into fooduser (Email, Food) values ('fjordan9a@acquirethisname.com', 'Saccharomyces cerevisiae');
insert into fooduser (Email, Food) values ('ehanson9b@cbc.ca', 'Gatifloxacin');
insert into fooduser (Email, Food) values ('lnelson9c@nasa.gov', 'citroma');
insert into fooduser (Email, Food) values ('athomas9d@upenn.edu', 'KROGER');
insert into fooduser (Email, Food) values ('eowens9e@paypal.com', 'Hizentra');
insert into fooduser (Email, Food) values ('astephens9f@cam.ac.uk', 'Nitrous Oxide');
insert into fooduser (Email, Food) values ('edavis9g@va.gov', 'smooth lax');
insert into fooduser (Email, Food) values ('jbowman9h@techcrunch.com', 'Mesquite');
insert into fooduser (Email, Food) values ('krichards9i@psu.edu', 'Triamterene and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('eross9j@sohu.com', 'ETHYL ALCOHOL');
insert into fooduser (Email, Food) values ('jwhite9k@ft.com', 'Johnson Grass');
insert into fooduser (Email, Food) values ('rstephens9l@miibeian.gov.cn', 'Degree');
insert into fooduser (Email, Food) values ('jroberts9m@alibaba.com', 'Anti Bacterial Foam Hand Problend');
insert into fooduser (Email, Food) values ('pthompson9n@ifeng.com', 'Nitrous Oxide');
insert into fooduser (Email, Food) values ('tperkins9o@nyu.edu', 'Octreotide Acetate');
insert into fooduser (Email, Food) values ('kharrison9p@discovery.com', 'R2 System');
insert into fooduser (Email, Food) values ('mjones9q@ameblo.jp', 'Sulfamethoxazole and Trimethoprim');
insert into fooduser (Email, Food) values ('dferguson9r@amazonaws.com', 'Gas Relief');
insert into fooduser (Email, Food) values ('rdiaz9s@yelp.com', 'Bacitracin');
insert into fooduser (Email, Food) values ('dharrison9t@reference.com', 'Butalbital, Acetaminophen, and Caffeine');
insert into fooduser (Email, Food) values ('bwelch9u@pagesperso-orange.fr', 'Torsemide');
insert into fooduser (Email, Food) values ('acarpenter9v@blogtalkradio.com', 'AGARICUS MUSCARIUS');
insert into fooduser (Email, Food) values ('wmarshall9w@economist.com', 'Hydromorphone Hydrochloride');
insert into fooduser (Email, Food) values ('rhowell9x@amazon.de', 'Sodium Chloride');
insert into fooduser (Email, Food) values ('njacobs9y@wiley.com', 'Aspirin');
insert into fooduser (Email, Food) values ('sspencer9z@google.es', 'INVEGA SUSTENNA');
insert into fooduser (Email, Food) values ('ejamesa0@usda.gov', 'Gelato Topical Anesthetic');
insert into fooduser (Email, Food) values ('ejordana1@google.ca', 'Carbamazepine');
insert into fooduser (Email, Food) values ('crobinsona2@w3.org', 'ANTIBACTERIAL HAND SANITIZER');
insert into fooduser (Email, Food) values ('welliotta3@livejournal.com', 'Ibuprofen');
insert into fooduser (Email, Food) values ('pedwardsa4@timesonline.co.uk', 'RISPERDAL');
insert into fooduser (Email, Food) values ('abaileya5@geocities.com', 'ARC FIRST AID Contains 303 PIECES');
insert into fooduser (Email, Food) values ('gmeyera6@cafepress.com', 'Medline Peroxi Fresh');
insert into fooduser (Email, Food) values ('challa7@dmoz.org', 'Healthy Accents Antacid');
insert into fooduser (Email, Food) values ('rjohnstona8@google.ru', 'Flu and Severe Cold and Cough');
insert into fooduser (Email, Food) values ('ssimpsona9@intel.com', 'Dynamic Skin Recovery SPF30');
insert into fooduser (Email, Food) values ('wchapmanaa@flavors.me', 'SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)');
insert into fooduser (Email, Food) values ('mgrantab@nymag.com', 'LBEL COULEUR LUXE AMPLIFIER XP');
insert into fooduser (Email, Food) values ('bjacobsac@thetimes.co.uk', 'Muscle and Joint HRX');
insert into fooduser (Email, Food) values ('lshawad@bbb.org', 'Lactated Ringers and Dextrose');
insert into fooduser (Email, Food) values ('jhayesae@ebay.com', 'Risedronate Sodium');
insert into fooduser (Email, Food) values ('kmeyeraf@constantcontact.com', 'Venlafaxine hydrochloride');
insert into fooduser (Email, Food) values ('tthomasag@themeforest.net', 'Oxcarbazepine');
insert into fooduser (Email, Food) values ('dkellyah@yahoo.co.jp', 'Bupropion hydrochloride');
insert into fooduser (Email, Food) values ('twardai@wikia.com', 'Olive Leaf Throat');
insert into fooduser (Email, Food) values ('hromeroaj@studiopress.com', 'Arthritis Pain Reliever');
insert into fooduser (Email, Food) values ('lgonzalesak@bizjournals.com', 'Glandulae suprarenales 4');
insert into fooduser (Email, Food) values ('jwoodal@twitpic.com', 'pain relief');
insert into fooduser (Email, Food) values ('bfowleram@ibm.com', 'Coppertone Sport');
insert into fooduser (Email, Food) values ('hrichardsan@storify.com', 'Instant Hand sanitizer');
insert into fooduser (Email, Food) values ('rgarzaao@blogger.com', 'Bicalutamide');
insert into fooduser (Email, Food) values ('rreidap@blogspot.com', 'OXYCODONE AND ACETAMINOPHEN');
insert into fooduser (Email, Food) values ('doliveraq@360.cn', 'Lorazepam');
insert into fooduser (Email, Food) values ('egarciaar@samsung.com', 'SIMVASTATIN');
insert into fooduser (Email, Food) values ('rbrooksas@unicef.org', 'Effexor');
insert into fooduser (Email, Food) values ('pspencerat@alibaba.com', 'Aspirin');
insert into fooduser (Email, Food) values ('mreedau@taobao.com', 'ANTIBACTERIAL');
insert into fooduser (Email, Food) values ('dgonzalezav@dell.com', 'Duloxetine');
insert into fooduser (Email, Food) values ('klaneaw@nature.com', 'Marathon Pain Relief');
insert into fooduser (Email, Food) values ('kaustinax@dot.gov', 'Severe Allergy And Sinus Headache');
insert into fooduser (Email, Food) values ('jjacksonay@craigslist.org', 'Quetiapine fumarate');
insert into fooduser (Email, Food) values ('klarsonaz@dot.gov', 'Rimmel BB Beauty Balm');
insert into fooduser (Email, Food) values ('ablackb0@businessinsider.com', 'Petroleum Skin Protectant');
insert into fooduser (Email, Food) values ('smorrisonb1@latimes.com', 'Triple Antibiotic');
insert into fooduser (Email, Food) values ('ktuckerb2@wikimedia.org', 'Cilostazol');
insert into fooduser (Email, Food) values ('awestb3@bigcartel.com', 'Orajel');
insert into fooduser (Email, Food) values ('krogersb4@wordpress.com', 'clearlax');
insert into fooduser (Email, Food) values ('sbellb5@skype.com', 'Benazepril Hydrochloride');
insert into fooduser (Email, Food) values ('nharveyb6@behance.net', 'Vida Mia Hand Sanitizer');
insert into fooduser (Email, Food) values ('jwilliamsb7@amazon.com', 'Halog');
insert into fooduser (Email, Food) values ('smasonb8@sciencedaily.com', 'Ceftriaxone');
insert into fooduser (Email, Food) values ('mrichardsb9@is.gd', 'Cephalexin');
insert into fooduser (Email, Food) values ('lmendozaba@cdc.gov', 'Isopropyl alcohol');
insert into fooduser (Email, Food) values ('mhenrybb@myspace.com', 'ALLOPURINOL');
insert into fooduser (Email, Food) values ('arossbc@paginegialle.it', 'Ibuprofen PM');
insert into fooduser (Email, Food) values ('cdaybd@cdc.gov', 'Methocarbamol');
insert into fooduser (Email, Food) values ('voliverbe@dion.ne.jp', 'Senna and Docusate Sodium');
insert into fooduser (Email, Food) values ('ehenrybf@google.pl', 'Cabbage');
insert into fooduser (Email, Food) values ('clynchbg@dyndns.org', 'Lymphatic Drainer');
insert into fooduser (Email, Food) values ('emorganbh@weather.com', 'Juxtapid');
insert into fooduser (Email, Food) values ('cchapmanbi@omniture.com', 'Ecolab');
insert into fooduser (Email, Food) values ('rmitchellbj@ycombinator.com', 'Keppra');
insert into fooduser (Email, Food) values ('sgreenebk@over-blog.com', 'Diltiazem Hydrochloride');
insert into fooduser (Email, Food) values ('cchapmanbl@delicious.com', 'Total Chlorine');
insert into fooduser (Email, Food) values ('tlongbm@cafepress.com', 'Lymph Detox Plus');
insert into fooduser (Email, Food) values ('pburtonbn@weibo.com', 'PhysiciansCare Antacid');
insert into fooduser (Email, Food) values ('anelsonbo@multiply.com', 'Azelastine Hydrochloride');
insert into fooduser (Email, Food) values ('kwheelerbp@webmd.com', 'PlusPharma Extra Strength');
insert into fooduser (Email, Food) values ('rburkebq@cloudflare.com', 'Prevacid SoluTab');
insert into fooduser (Email, Food) values ('ktuckerbr@barnesandnoble.com', 'Tinactin');
insert into fooduser (Email, Food) values ('ewhitebs@seattletimes.com', 'VARIVAX');
insert into fooduser (Email, Food) values ('cmccoybt@livejournal.com', 'Soothe Hydration');
insert into fooduser (Email, Food) values ('jwardbu@digg.com', 'Walgreen Sensitive Extra Whitening');
insert into fooduser (Email, Food) values ('bsnyderbv@rambler.ru', 'Octreotide Acetate');
insert into fooduser (Email, Food) values ('thamiltonbw@ezinearticles.com', 'Technetium Tc99m Generator');
insert into fooduser (Email, Food) values ('mspencerbx@bbb.org', 'Hot Flashes');
insert into fooduser (Email, Food) values ('tdiazby@weather.com', 'Dr G deWrinkle REFORMER by EGF');
insert into fooduser (Email, Food) values ('lsnyderbz@storify.com', 'Hydrocodone Bitartrate And Acetaminophen');
insert into fooduser (Email, Food) values ('preidc0@pagesperso-orange.fr', 'Ondansetron');
insert into fooduser (Email, Food) values ('hkingc1@mit.edu', 'Intralipid');
insert into fooduser (Email, Food) values ('hhendersonc2@mozilla.com', 'Homeopathic Womens Libido');
insert into fooduser (Email, Food) values ('fchavezc3@google.de', 'Trazodone Hydrochloride');
insert into fooduser (Email, Food) values ('agilbertc4@facebook.com', 'Alka-Seltzer Plus');
insert into fooduser (Email, Food) values ('rmccoyc5@hud.gov', 'Butalbital, Acetaminophen and Caffeine');
insert into fooduser (Email, Food) values ('bramosc6@washington.edu', 'HCG Plus');
insert into fooduser (Email, Food) values ('tcarrc7@howstuffworks.com', 'Lobelia Inflata');
insert into fooduser (Email, Food) values ('phayesc8@merriam-webster.com', 'Anti-Aging Tinted Moisturizer Broad Spectrum SPF 30');
insert into fooduser (Email, Food) values ('jcookc9@yellowbook.com', 'Ocean Potion Quick Dry 30 Sunscreen');
insert into fooduser (Email, Food) values ('pbaileyca@hexun.com', 'ALOE VESTA PROTECTIVE BARRIER');
insert into fooduser (Email, Food) values ('lsmithcb@hatena.ne.jp', 'Modafinil');
insert into fooduser (Email, Food) values ('jfieldscc@gravatar.com', 'stomach relief');
insert into fooduser (Email, Food) values ('mgarzacd@wsj.com', 'Crisp Apple Hand Sani');
insert into fooduser (Email, Food) values ('srodriguezce@un.org', 'Lunesta');
insert into fooduser (Email, Food) values ('ssimpsoncf@nifty.com', 'Atorvastatin Calcium');
insert into fooduser (Email, Food) values ('barmstrongcg@spiegel.de', 'ESIKA');
insert into fooduser (Email, Food) values ('rpaynech@ask.com', 'Nerve Pain Relief');
insert into fooduser (Email, Food) values ('tgutierrezci@tumblr.com', 'Watermelon');
insert into fooduser (Email, Food) values ('fallencj@statcounter.com', 'Clotrimazole');
insert into fooduser (Email, Food) values ('mrayck@ucla.edu', 'Select Brand Burn Relief');
insert into fooduser (Email, Food) values ('mgrahamcl@guardian.co.uk', 'Moore Medical Antacid');
insert into fooduser (Email, Food) values ('rwhitecm@cnn.com', 'VITALUMIERE AQUA');
insert into fooduser (Email, Food) values ('whartcn@trellian.com', 'Flecainide Acetate');
insert into fooduser (Email, Food) values ('jwoodco@ning.com', 'Amlodipine Besylate and Benazepril Hydrochloride');
insert into fooduser (Email, Food) values ('krobinsoncp@chronoengine.com', 'VERELAN');
insert into fooduser (Email, Food) values ('gfreemancq@barnesandnoble.com', 'Meclizine HCl');
insert into fooduser (Email, Food) values ('sbennettcr@ox.ac.uk', 'Oxygen');
insert into fooduser (Email, Food) values ('dsanchezcs@wikia.com', 'Bambusa Rhus');
insert into fooduser (Email, Food) values ('mhayesct@bing.com', 'ABILIFY');
insert into fooduser (Email, Food) values ('araycu@weather.com', 'NovoLog');
insert into fooduser (Email, Food) values ('bbutlercv@rambler.ru', 'Levetiracetam');
insert into fooduser (Email, Food) values ('astephenscw@nhs.uk', 'Cilostazol');
insert into fooduser (Email, Food) values ('gdaviscx@pen.io', 'Antimicrobial Hand Sanitizer');
insert into fooduser (Email, Food) values ('lcarpentercy@slideshare.net', 'B-Nexa');
insert into fooduser (Email, Food) values ('ahernandezcz@constantcontact.com', 'Donepezil Hydrochloride');
insert into fooduser (Email, Food) values ('balvarezd0@liveinternet.ru', 'equaline infants pain and fever');
insert into fooduser (Email, Food) values ('bevansd1@ow.ly', 'LEVAQUIN');
insert into fooduser (Email, Food) values ('jsullivand2@utexas.edu', 'Ascorbic Acid');
insert into fooduser (Email, Food) values ('aharperd3@cnn.com', 'Simvastatin');
insert into fooduser (Email, Food) values ('scrawfordd4@arstechnica.com', 'MOZI-Qfor kids and infa');
insert into fooduser (Email, Food) values ('cwellsd5@symantec.com', 'ibuprofen');
insert into fooduser (Email, Food) values ('nwarrend6@wisc.edu', 'Arnica 10% First Aid');
insert into fooduser (Email, Food) values ('jrileyd7@com.com', 'Cover Tint');
insert into fooduser (Email, Food) values ('dfullerd8@ameblo.jp', 'LBEL EFFET PARFAIT MINERAL NATURAL SKIN EFFECT MOUSSE FOUNDATION SPF 16');
insert into fooduser (Email, Food) values ('bandrewsd9@goo.gl', 'Temazepam');
insert into fooduser (Email, Food) values ('jhartda@cbslocal.com', 'AntiBac Foam Wash/Aerogreen');
insert into fooduser (Email, Food) values ('cblackdb@blogger.com', 'Venlafaxine hydrochloride');
insert into fooduser (Email, Food) values ('bcampbelldc@ucla.edu', 'Lidocaine HCl');
insert into fooduser (Email, Food) values ('estanleydd@earthlink.net', 'Misoprostol');
insert into fooduser (Email, Food) values ('sstephensde@g.co', 'Primula Scilla');
insert into fooduser (Email, Food) values ('sforddf@quantcast.com', 'Lil Drug Store Pain Relief');
insert into fooduser (Email, Food) values ('rhamiltondg@netscape.com', 'Cefepime');
insert into fooduser (Email, Food) values ('mgriffindh@craigslist.org', 'Metoclopramide');
insert into fooduser (Email, Food) values ('pjacobsdi@biblegateway.com', 'LOESTRIN 1.5/30');
insert into fooduser (Email, Food) values ('ealexanderdj@mozilla.com', 'SURFAXIN');
insert into fooduser (Email, Food) values ('radamsdk@fastcompany.com', 'OXYBUTYNIN CHLORIDE');
insert into fooduser (Email, Food) values ('pcoledl@tamu.edu', 'Apis ex animale 3 Special Order');
insert into fooduser (Email, Food) values ('lkimdm@guardian.co.uk', 'Nystatin');
insert into fooduser (Email, Food) values ('dgrantdn@qq.com', 'BIRDS GARDEN LIP BALM');
insert into fooduser (Email, Food) values ('nkennedydo@ox.ac.uk', 'Tramadol Hydrochloride');
insert into fooduser (Email, Food) values ('mgarrettdp@whitehouse.gov', 'Antibacterial Foaming Hand Sanitizer');
insert into fooduser (Email, Food) values ('bphillipsdq@usa.gov', 'Therapeutic Plus');
insert into fooduser (Email, Food) values ('tperkinsdr@ow.ly', 'Childrens Plus Multi-Symptom');
insert into fooduser (Email, Food) values ('ahuntds@vimeo.com', 'Arniflora');
insert into fooduser (Email, Food) values ('randersondt@mapquest.com', 'LBEL COULEUR LUXE AMPLIFIER XP');
insert into fooduser (Email, Food) values ('kdanielsdu@merriam-webster.com', 'PREPARATION H MEDICATED WIPES FOR WOMEN');
insert into fooduser (Email, Food) values ('vmyersdv@ucoz.com', 'Eve Lom Radiance Lift Foundation SPF 15');
insert into fooduser (Email, Food) values ('swarrendw@lycos.com', 'Simvastatin');
insert into fooduser (Email, Food) values ('dhendersondx@ning.com', 'GODDESS GARDEN ORGANICS Tangerine Lavender DAILY BROAD SPECTRUM SPF 15');
insert into fooduser (Email, Food) values ('mrobinsondy@shinystat.com', 'DIGOX');
insert into fooduser (Email, Food) values ('nmorrisdz@google.it', 'Rite Aid');
insert into fooduser (Email, Food) values ('nrobertsone0@techcrunch.com', 'STEMPHYLIUM SARCINIFORME');
insert into fooduser (Email, Food) values ('dgarrette1@weibo.com', 'Benztropine Mesylate');
insert into fooduser (Email, Food) values ('sstanleye2@i2i.jp', 'KSS CLEAN HANDS ANTISEPTIC CLEANER');
insert into fooduser (Email, Food) values ('lelliotte3@icq.com', 'PHOTOSHOT 3D BB BALM');
insert into fooduser (Email, Food) values ('pgeorgee4@huffingtonpost.com', 'Imipenem and Cilastatin');
insert into fooduser (Email, Food) values ('cmcdonalde5@china.com.cn', 'Nice');
insert into fooduser (Email, Food) values ('cthompsone6@aol.com', 'ATORVASTATIN CALCIUM');
insert into fooduser (Email, Food) values ('rcarre7@flickr.com', 'Nifedipine');
insert into fooduser (Email, Food) values ('nmartineze8@deviantart.com', 'SENSODYNE');
insert into fooduser (Email, Food) values ('dbowmane9@chicagotribune.com', 'glydo');
insert into fooduser (Email, Food) values ('sowensea@house.gov', 'chewable');
insert into fooduser (Email, Food) values ('ldunneb@photobucket.com', 'NARS');
insert into fooduser (Email, Food) values ('lwoodec@mtv.com', 'Soft Care Neutra Germ Fragrance Free Antibacterial');
insert into fooduser (Email, Food) values ('dwoodsed@wp.com', 'Mycophenolate Mofetil');
insert into fooduser (Email, Food) values ('nsimpsonee@networksolutions.com', 'CY BETTER LIPS BALM Humectante para Labios con color FPS 18');
insert into fooduser (Email, Food) values ('dwrightef@nasa.gov', 'SUGAR FREE SWISS CHERRY HERB THROAT DROPS');
insert into fooduser (Email, Food) values ('dfergusoneg@typepad.com', 'nasal decongestant');
insert into fooduser (Email, Food) values ('pstevenseh@artisteer.com', 'Rexall Ibuprofen');
insert into fooduser (Email, Food) values ('gmorrisonei@msu.edu', 'Clario Foaming Alcohol Instant Hand Sanitizer');
insert into fooduser (Email, Food) values ('jsanchezej@craigslist.org', 'Keppra');
insert into fooduser (Email, Food) values ('abishopek@washington.edu', 'Blistex Enhancement Series (Lip Vibrance, Deep Renewal and Ultra-Rich Hydration)');
insert into fooduser (Email, Food) values ('jmasonel@buzzfeed.com', 'Health Care Personnel Handwash');
insert into fooduser (Email, Food) values ('egarrettem@is.gd', 'Gabapentin');
insert into fooduser (Email, Food) values ('rfoxen@hostgator.com', 'Anxiety Relief');
insert into fooduser (Email, Food) values ('cbishopeo@shop-pro.jp', 'LARIN Fe 1/20');
insert into fooduser (Email, Food) values ('sgarrettep@buzzfeed.com', 'Undesine');
insert into fooduser (Email, Food) values ('pchavezeq@sohu.com', 'Itchy Eye Drops');
insert into fooduser (Email, Food) values ('drosser@eventbrite.com', 'Amoxicillin');
insert into fooduser (Email, Food) values ('jwhitees@goodreads.com', 'Amlodipine and Atorvastatin');
insert into fooduser (Email, Food) values ('pjacobset@mozilla.org', 'Good Sense Severe NightTime Cold and Flu');
insert into fooduser (Email, Food) values ('awilsoneu@hexun.com', 'Acetylcysteine');
insert into fooduser (Email, Food) values ('kperryev@scientificamerican.com', 'Senna-Lax');
insert into fooduser (Email, Food) values ('gfloresew@newsvine.com', 'ANACARDIUM ORIENTALE');
insert into fooduser (Email, Food) values ('rmillerex@hexun.com', 'Black Olive');
insert into fooduser (Email, Food) values ('sbutlerey@icq.com', 'VERAPAMIL HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('jjacksonez@usgs.gov', 'Foltabs 800');
insert into fooduser (Email, Food) values ('rjacksonf0@printfriendly.com', 'Antibacterial Wet Wipes');
insert into fooduser (Email, Food) values ('lscottf1@unicef.org', 'Rejuvenate 2000 Maximum Strength Formula For Men');
insert into fooduser (Email, Food) values ('sbaileyf2@ocn.ne.jp', 'ShopKo Absolute Daily Moisturizer SPF15 Sensitive Skin');
insert into fooduser (Email, Food) values ('lmasonf3@slideshare.net', 'StingMed');
insert into fooduser (Email, Food) values ('cwatkinsf4@vkontakte.ru', 'potassium phosphates');
insert into fooduser (Email, Food) values ('bcolemanf5@hhs.gov', 'NovoLog Mix 70/30');
insert into fooduser (Email, Food) values ('mandrewsf6@phpbb.com', 'Dove');
insert into fooduser (Email, Food) values ('cturnerf7@livejournal.com', 'Nighttime');
insert into fooduser (Email, Food) values ('ghansonf8@ebay.co.uk', 'Apraclonidine Ophthalmic');
insert into fooduser (Email, Food) values ('showardf9@oracle.com', 'Laneige sliding pact EX');
insert into fooduser (Email, Food) values ('rwilsonfa@fastcompany.com', 'Chlordiazepoxide Hydrochloride');
insert into fooduser (Email, Food) values ('jburnsfb@skype.com', 'up and up minoxidil');
insert into fooduser (Email, Food) values ('rfosterfc@google.fr', 'Oxycodone and Acetaminophen');
insert into fooduser (Email, Food) values ('abaileyfd@instagram.com', 'good neighbor pharmacy Loperamide hydrochloride');
insert into fooduser (Email, Food) values ('smontgomeryfe@theglobeandmail.com', 'EQUATE');
insert into fooduser (Email, Food) values ('jwilliamsff@issuu.com', 'Colgate MaxFresh Fresh Mint');
insert into fooduser (Email, Food) values ('sgarzafg@buzzfeed.com', 'Technetium Tc99m Generator');
insert into fooduser (Email, Food) values ('sfieldsfh@dailymail.co.uk', 'Preferred Plus Maximum Strength Urinary Pain Relief');
insert into fooduser (Email, Food) values ('psanchezfi@exblog.jp', 'THINKSPORT');
insert into fooduser (Email, Food) values ('psimpsonfj@zimbio.com', 'Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate and Amphetamine Sulfate');
insert into fooduser (Email, Food) values ('rrayfk@cam.ac.uk', 'TRAMADOL HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('ebellfl@mediafire.com', 'equaline allergy');
insert into fooduser (Email, Food) values ('dgonzalezfm@themeforest.net', 'Naproxen');
insert into fooduser (Email, Food) values ('scastillofn@opensource.org', 'Phentermine Hydrochloride');
insert into fooduser (Email, Food) values ('epaynefo@home.pl', 'Lorazepam');
insert into fooduser (Email, Food) values ('amasonfp@fastcompany.com', 'Folic Acid');
insert into fooduser (Email, Food) values ('acoxfq@simplemachines.org', 'Ciprofloxacin');
insert into fooduser (Email, Food) values ('mfrazierfr@accuweather.com', 'Marcaine');
insert into fooduser (Email, Food) values ('dpetersonfs@hatena.ne.jp', 'Simply Numb Endure');
insert into fooduser (Email, Food) values ('kpalmerft@vkontakte.ru', 'Suave');
insert into fooduser (Email, Food) values ('ebryantfu@squidoo.com', 'desonide');
insert into fooduser (Email, Food) values ('carmstrongfv@phpbb.com', 'Benztropine Mesylate');
insert into fooduser (Email, Food) values ('tcookfw@mozilla.org', 'METHOTREXATE');
insert into fooduser (Email, Food) values ('wlanefx@ftc.gov', 'Isosorbide Mononitrate');
insert into fooduser (Email, Food) values ('shunterfy@amazon.de', 'Bacitracin Zinc');
insert into fooduser (Email, Food) values ('dmillsfz@com.com', 'Fragmin');
insert into fooduser (Email, Food) values ('flewisg0@java.com', 'Desoximetasone');
insert into fooduser (Email, Food) values ('amorrisg1@twitter.com', 'FibroFree Complex');
insert into fooduser (Email, Food) values ('jjohnsong2@sakura.ne.jp', 'Goldenrod');
insert into fooduser (Email, Food) values ('bcarrollg3@google.fr', 'Droperidol');
insert into fooduser (Email, Food) values ('nsullivang4@moonfruit.com', 'PROVIGIL');
insert into fooduser (Email, Food) values ('pbaileyg5@weibo.com', 'Flulaval Quadrivalent');
insert into fooduser (Email, Food) values ('rwilsong6@icio.us', 'IFEX');
insert into fooduser (Email, Food) values ('cmorenog7@jugem.jp', 'Ibuprofen');
insert into fooduser (Email, Food) values ('kfieldsg8@cbc.ca', 'Blistex Lip');
insert into fooduser (Email, Food) values ('jhansong9@shareasale.com', 'AMARANTHUS PALMERI POLLEN');
insert into fooduser (Email, Food) values ('rgordonga@sfgate.com', 'Nausea');
insert into fooduser (Email, Food) values ('sricegb@answers.com', 'Necon');
insert into fooduser (Email, Food) values ('emyersgc@washingtonpost.com', 'Levetiracetam');
insert into fooduser (Email, Food) values ('rhamiltongd@slideshare.net', 'Nice');
insert into fooduser (Email, Food) values ('mjohnsonge@baidu.com', 'Cepacol');
insert into fooduser (Email, Food) values ('cfranklingf@storify.com', 'FENTANYL');
insert into fooduser (Email, Food) values ('amillsgg@fda.gov', 'Methylphenidate Hydrochloride');
insert into fooduser (Email, Food) values ('athompsongh@youtube.com', 'Erythromycin Base');
insert into fooduser (Email, Food) values ('pscottgi@usatoday.com', 'The Gargle');
insert into fooduser (Email, Food) values ('aturnergj@liveinternet.ru', 'Weight Loss XL');
insert into fooduser (Email, Food) values ('ewilsongk@i2i.jp', 'Mark 3');
insert into fooduser (Email, Food) values ('hbowmangl@barnesandnoble.com', 'Flucytosine');
insert into fooduser (Email, Food) values ('darnoldgm@businesswire.com', 'bareMinerals Prime Time BB Primer Daily Defense Broad Spectrum SPF 30');
insert into fooduser (Email, Food) values ('solivergn@independent.co.uk', 'Cold and Hot Medicated Pain Relief Small');
insert into fooduser (Email, Food) values ('hcoxgo@mtv.com', 'Alcohol Prep Pads Lightweight Non-Sterile');
insert into fooduser (Email, Food) values ('rsimsgp@ifeng.com', 'Crinone');
insert into fooduser (Email, Food) values ('jrichardsgq@linkedin.com', 'Trazodone Hydrochloride');
insert into fooduser (Email, Food) values ('drobinsongr@eventbrite.com', 'Treatment Set TS335101');
insert into fooduser (Email, Food) values ('mdanielsgs@amazon.com', 'Benazepril Hydrochloride');
insert into fooduser (Email, Food) values ('fperkinsgt@ft.com', 'Balmex Diaper Rash');
insert into fooduser (Email, Food) values ('cevansgu@webeden.co.uk', 'Cold Sore Treatment');
insert into fooduser (Email, Food) values ('mbowmangv@oaic.gov.au', 'Eve Lom Radiance Perfected Tinted Moisturiser Broad Spectrum SPF 15 Sunscreen');
insert into fooduser (Email, Food) values ('ddiazgw@netlog.com', 'Guanfacine Hydrochloride');
insert into fooduser (Email, Food) values ('jmcdonaldgx@de.vu', 'Ceftriaxone');
insert into fooduser (Email, Food) values ('rpetersgy@ted.com', 'Nortriptyline Hydrochloride');
insert into fooduser (Email, Food) values ('lallengz@opensource.org', 'STUDIO 35');
insert into fooduser (Email, Food) values ('jbanksh0@msn.com', 'Old Spice High Endurance Clear');
insert into fooduser (Email, Food) values ('sgonzalezh1@about.com', 'ZONISAMIDE');
insert into fooduser (Email, Food) values ('pbennetth2@yelp.com', 'BabyGanics Sunscreen');
insert into fooduser (Email, Food) values ('mturnerh3@slate.com', 'Fosinopril Sodium');
insert into fooduser (Email, Food) values ('aperryh4@so-net.ne.jp', 'Citalopram Hydrobromide');
insert into fooduser (Email, Food) values ('phenryh5@wired.com', 'Hyoscyamine Sulfate SL');
insert into fooduser (Email, Food) values ('pwarrenh6@trellian.com', 'WERA');
insert into fooduser (Email, Food) values ('arodriguezh7@pinterest.com', 'Nupercainal Bio-Active Hemorrhoidal');
insert into fooduser (Email, Food) values ('cbutlerh8@berkeley.edu', 'Metoprolol Tartrate');
insert into fooduser (Email, Food) values ('msimpsonh9@google.es', 'PhysiciansCare Non Aspirin');
insert into fooduser (Email, Food) values ('clawrenceha@slate.com', 'Lidocaine Hydrochloride and Epinephrine');
insert into fooduser (Email, Food) values ('gdayhb@youtu.be', 'allergy');
insert into fooduser (Email, Food) values ('edixonhc@tumblr.com', 'ZIT ZAPPER');
insert into fooduser (Email, Food) values ('mandrewshd@eventbrite.com', 'Gentamicin Sulfate');
insert into fooduser (Email, Food) values ('hbrookshe@ovh.net', 'AMPHOTEC');
insert into fooduser (Email, Food) values ('lrichardshf@phpbb.com', 'Fentanyl Citrate');
insert into fooduser (Email, Food) values ('dthompsonhg@ucoz.ru', 'Benzonatate');
insert into fooduser (Email, Food) values ('jlarsonhh@hibu.com', 'Clarithromycin');
insert into fooduser (Email, Food) values ('kdeanhi@intel.com', 'TEMAZEPAM');
insert into fooduser (Email, Food) values ('pwillishj@gizmodo.com', 'Childrens Fever Reducer and Pain Reliever');
insert into fooduser (Email, Food) values ('pknighthk@4shared.com', 'Lidocaine Hydrochloride');
insert into fooduser (Email, Food) values ('hjameshl@oaic.gov.au', 'good neighbor pharmacy lice treatment');
insert into fooduser (Email, Food) values ('mwagnerhm@apache.org', 'DayTime NightTime Sinus Relief');
insert into fooduser (Email, Food) values ('wharthn@sbwire.com', 'Terapie Anti-Fungal');
insert into fooduser (Email, Food) values ('bfergusonho@quantcast.com', 'Terrasil Foot and Nail Anti-Fungal');
insert into fooduser (Email, Food) values ('bperezhp@goo.gl', 'Brewers Yeast');
insert into fooduser (Email, Food) values ('cknighthq@ucla.edu', 'Blistex');
insert into fooduser (Email, Food) values ('pfordhr@admin.ch', 'Nux Vomica Homaccord');
insert into fooduser (Email, Food) values ('rowenshs@vk.com', 'Ketoconazole');
insert into fooduser (Email, Food) values ('wscottht@delicious.com', 'Couch Quack Grass');
insert into fooduser (Email, Food) values ('elawsonhu@alibaba.com', 'Sun Face Protector Sunscreen Broad Spectrum SPF 50');
insert into fooduser (Email, Food) values ('rmillshv@trellian.com', 'Potassium Chloride');
insert into fooduser (Email, Food) values ('nfernandezhw@digg.com', 'Patricia Wexler Skin Brightening Daily Moisturizer with Sunscreen Broad Spectrum SPF 28');
insert into fooduser (Email, Food) values ('apricehx@hatena.ne.jp', 'DiorSkin Nude 023 Peach');
insert into fooduser (Email, Food) values ('balexanderhy@behance.net', 'CLADOSPORIUM SPHAEROSPERMUM');
insert into fooduser (Email, Food) values ('twrighthz@blinklist.com', 'Intralipid');
insert into fooduser (Email, Food) values ('nharrisoni0@wix.com', 'HASOL Intensive Scalp Tonic');
insert into fooduser (Email, Food) values ('cjacobsi1@prnewswire.com', 'PVP Scrub');
insert into fooduser (Email, Food) values ('npetersi2@behance.net', 'SPF 30 Sunscreen');
insert into fooduser (Email, Food) values ('aowensi3@apache.org', 'PENICILLIN G POTASSIUM');
insert into fooduser (Email, Food) values ('dmatthewsi4@godaddy.com', 'Naproxen Sodium');
insert into fooduser (Email, Food) values ('hschmidti5@hc360.com', 'Mold Mix Antigens');
insert into fooduser (Email, Food) values ('soliveri6@opensource.org', 'DOCUSATE SODIUM');
insert into fooduser (Email, Food) values ('cwardi7@diigo.com', 'levalbuterol inhalation');
insert into fooduser (Email, Food) values ('ksanchezi8@google.cn', 'Male Complex');
insert into fooduser (Email, Food) values ('ssmithi9@networksolutions.com', 'Amoxicillin');
insert into fooduser (Email, Food) values ('lhayesia@biglobe.ne.jp', 'LOreal Paris Revitalift Miracle Blur Broad Spectrum SPF 30 Sunscreen');
insert into fooduser (Email, Food) values ('emedinaib@addthis.com', 'JNH Ato-Care Super Barried ATO-Serum');
insert into fooduser (Email, Food) values ('mrobertsic@dropbox.com', 'LISINOPRIL AND HYDROCHLOROTHIAZIDE');
insert into fooduser (Email, Food) values ('jmartinid@home.pl', 'AHC Whitening Special Gen Cream');
insert into fooduser (Email, Food) values ('acoxie@tinyurl.com', 'Topcare Fiber Laxative');
insert into fooduser (Email, Food) values ('phendersonif@slideshare.net', 'Ganciclovir');
insert into fooduser (Email, Food) values ('sthomasig@nasa.gov', 'ZINC OXIDE');
insert into fooduser (Email, Food) values ('dcampbellih@europa.eu', 'SUPPRELIN');
insert into fooduser (Email, Food) values ('dfullerii@yahoo.co.jp', 'Fexofenadine');
insert into fooduser (Email, Food) values ('hmendozaij@utexas.edu', 'Siltussin DM');
insert into fooduser (Email, Food) values ('amorenoik@sitemeter.com', 'Verapamil');
insert into fooduser (Email, Food) values ('kleeil@ycombinator.com', 'ATORVASTATIN CALCIUM');
insert into fooduser (Email, Food) values ('jlawsonim@weibo.com', 'Long Acting Tussin Cough Gels');
insert into fooduser (Email, Food) values ('dparkerin@123-reg.co.uk', 'HyVee');
insert into fooduser (Email, Food) values ('nsmithio@bravesites.com', 'Soothe and Cool Fresh Dandruff Control');
insert into fooduser (Email, Food) values ('cbellip@yellowpages.com', 'Venlafaxine Hydrochloride');
insert into fooduser (Email, Food) values ('srayiq@arizona.edu', 'Topiramate');
insert into fooduser (Email, Food) values ('rwatkinsir@skyrock.com', 'Penicillium notatum');
insert into fooduser (Email, Food) values ('chuntis@shutterfly.com', 'wal tussin dm');
insert into fooduser (Email, Food) values ('bhallit@mysql.com', 'ExeClear');
insert into fooduser (Email, Food) values ('afosteriu@apache.org', 'ibuprofen pm');
insert into fooduser (Email, Food) values ('rrodrigueziv@rediff.com', 'Clindamycin Hydrochloride');
insert into fooduser (Email, Food) values ('lfordiw@illinois.edu', 'LAMICTAL');
insert into fooduser (Email, Food) values ('elawrenceix@bloglovin.com', 'American Beech');
insert into fooduser (Email, Food) values ('bdiaziy@census.gov', 'Mag-Al Plus');
insert into fooduser (Email, Food) values ('dfloresiz@homestead.com', 'Lil Drug Store NoSnooze');
insert into fooduser (Email, Food) values ('hallenj0@latimes.com', 'hCG Formula');
insert into fooduser (Email, Food) values ('jjordanj1@vk.com', 'Dr.Jart Black Label Detox BB Beaty Balm');
insert into fooduser (Email, Food) values ('nsandersj2@deliciousdays.com', 'MedPride');
insert into fooduser (Email, Food) values ('nbishopj3@princeton.edu', 'Axe');
insert into fooduser (Email, Food) values ('jhawkinsj4@skype.com', 'Exuviance CoverBlend Concealing Treatment Makeup');
insert into fooduser (Email, Food) values ('acastilloj5@wordpress.org', 'Good Sense Hair Regrowth Treatment');
insert into fooduser (Email, Food) values ('cowensj6@mit.edu', 'Anti-Bacterial Hand Sanitizer');
insert into fooduser (Email, Food) values ('dgrahamj7@amazonaws.com', 'Daptomycin');
insert into fooduser (Email, Food) values ('amoralesj8@java.com', 'Ceramide Lift And Firm Makeup Broad Spectrum Sunscreen SPF 15 Cameo');
insert into fooduser (Email, Food) values ('dduncanj9@yellowbook.com', 'Hemorrhoidal Hygiene pads');
insert into fooduser (Email, Food) values ('rdixonja@weather.com', 'LETROZOLE');
insert into fooduser (Email, Food) values ('srobertsonjb@yahoo.co.jp', 'Methocarbamol');
insert into fooduser (Email, Food) values ('rgonzalezjc@prlog.org', 'Breast Cyst and Discomforts');
insert into fooduser (Email, Food) values ('rwallacejd@webnode.com', 'Golden Sunshine Far Infrared HOT Herbal');
insert into fooduser (Email, Food) values ('rgonzalesje@icio.us', 'CRAB');
insert into fooduser (Email, Food) values ('smorrisonjf@ucsd.edu', 'Rosmarinus Argentum');
insert into fooduser (Email, Food) values ('jfosterjg@edublogs.org', 'SH18 Skin Lightening');
insert into fooduser (Email, Food) values ('rgarzajh@free.fr', 'LEVOTHYROXINE SODIUM');
insert into fooduser (Email, Food) values ('lscottji@unblog.fr', 'Zodryl DEC 30');
insert into fooduser (Email, Food) values ('mwilliamsonjj@va.gov', 'Bupropion hydrochloride4b17de');
insert into fooduser (Email, Food) values ('lclarkjk@statcounter.com', 'EQUUS CABALLUS SKIN');
insert into fooduser (Email, Food) values ('dalexanderjl@tuttocitta.it', 'Metoprolol succinate');
insert into fooduser (Email, Food) values ('aburnsjm@lulu.com', 'MVC-Fluoride');
insert into fooduser (Email, Food) values ('fkennedyjn@nymag.com', 'Bicalutamide');
insert into fooduser (Email, Food) values ('mfreemanjo@foxnews.com', 'Enalapril Maleate and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('akingjp@123-reg.co.uk', 'MooreBrand Ibuprofen');
insert into fooduser (Email, Food) values ('mbrownjq@sfgate.com', 'Gnaphalium Stannum');
insert into fooduser (Email, Food) values ('wkennedyjr@umn.edu', 'Lamotrigine');
insert into fooduser (Email, Food) values ('cnguyenjs@fastcompany.com', 'Pain Relief Extra Strength');
insert into fooduser (Email, Food) values ('mfranklinjt@hud.gov', 'stop hair');
insert into fooduser (Email, Food) values ('bmillerju@usda.gov', 'Chlordiazepoxide and Amitriptyline Hydrochloride');
insert into fooduser (Email, Food) values ('rrobinsonjv@cbslocal.com', 'Alphanate');
insert into fooduser (Email, Food) values ('hrodriguezjw@google.co.uk', 'ibuprofen');
insert into fooduser (Email, Food) values ('mgrantjx@statcounter.com', 'Old Spice Classic');
insert into fooduser (Email, Food) values ('jlopezjy@livejournal.com', 'healthy accents antacid');
insert into fooduser (Email, Food) values ('jwillisjz@hexun.com', 'Pantoprazole Sodium');
insert into fooduser (Email, Food) values ('eryank0@paginegialle.it', 'Oxcarbazepine');
insert into fooduser (Email, Food) values ('dbennettk1@elegantthemes.com', 'pain and fever');
insert into fooduser (Email, Food) values ('scooperk2@addthis.com', 'Venlafaxine');
insert into fooduser (Email, Food) values ('mcruzk3@wix.com', 'Lovenox');
insert into fooduser (Email, Food) values ('jallenk4@naver.com', 'Felodipine');
insert into fooduser (Email, Food) values ('sromerok5@nsw.gov.au', 'Goats Milk');
insert into fooduser (Email, Food) values ('jgrayk6@qq.com', 'Zidovudine');
insert into fooduser (Email, Food) values ('fstevensk7@fotki.com', 'Dr. Super Khan');
insert into fooduser (Email, Food) values ('jmatthewsk8@ow.ly', 'SeptoSan');
insert into fooduser (Email, Food) values ('mgonzalezk9@census.gov', 'ChloraPrep One-Step');
insert into fooduser (Email, Food) values ('lwilsonka@feedburner.com', 'Ulta Sparkling Lemon Anti-Bacterial Deep Cleansing');
insert into fooduser (Email, Food) values ('smatthewskb@digg.com', 'VASOPRESSIN');
insert into fooduser (Email, Food) values ('jkennedykc@dell.com', 'Hydrocortisone Maximum Strength');
insert into fooduser (Email, Food) values ('jmurphykd@nytimes.com', 'benzoyl peroxide');
insert into fooduser (Email, Food) values ('mmorenoke@wikispaces.com', 'Super Restorative Foundation True Lift SPF 15 Tint 08');
insert into fooduser (Email, Food) values ('sfrazierkf@xrea.com', 'all day relief');
insert into fooduser (Email, Food) values ('sleekg@w3.org', 'Zolmitriptan Orally Disintegrating');
insert into fooduser (Email, Food) values ('smurraykh@stanford.edu', 'Jantoven');
insert into fooduser (Email, Food) values ('alopezki@tinyurl.com', 'Eucalyptus');
insert into fooduser (Email, Food) values ('mspencerkj@fotki.com', 'DICYCLOMINE HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('acruzkk@scientificamerican.com', 'GO TIME');
insert into fooduser (Email, Food) values ('wgomezkl@who.int', 'Amitriptyline Hydrochloride');
insert into fooduser (Email, Food) values ('rwilliamsonkm@java.com', 'Oxygen-Nitrogen Mixture');
insert into fooduser (Email, Food) values ('jcarterkn@amazon.de', 'Plantain Beeswax Cough Relief');
insert into fooduser (Email, Food) values ('chenryko@yelp.com', 'Yellow Sweet Clover');
insert into fooduser (Email, Food) values ('mhernandezkp@sbwire.com', 'Pentoxifylline');
insert into fooduser (Email, Food) values ('doliverkq@google.com.au', 'Anxiety HP');
insert into fooduser (Email, Food) values ('hcrawfordkr@flickr.com', 'Clemastine Fumarate');
insert into fooduser (Email, Food) values ('bhowardks@dailymotion.com', 'Thiamine Hydrochloride');
insert into fooduser (Email, Food) values ('pmitchellkt@ow.ly', 'Hydrocortisone');
insert into fooduser (Email, Food) values ('kfowlerku@skyrock.com', 'Terocin');
insert into fooduser (Email, Food) values ('jbowmankv@youtube.com', 'Phenazo');
insert into fooduser (Email, Food) values ('mraykw@berkeley.edu', 'N-Con Tonic');
insert into fooduser (Email, Food) values ('rolsonkx@nyu.edu', 'Foundation Primer SPF 15');
insert into fooduser (Email, Food) values ('adixonky@360.cn', 'Oxycodone and Acetaminophen');
insert into fooduser (Email, Food) values ('lrogerskz@xing.com', 'Rite Aid Sensitive Mint');
insert into fooduser (Email, Food) values ('slynchl0@umn.edu', 'Chlordiazepoxide Hydrochloride');
insert into fooduser (Email, Food) values ('cchapmanl1@aol.com', 'Diazepam');
insert into fooduser (Email, Food) values ('jramirezl2@gnu.org', 'Parlodel');
insert into fooduser (Email, Food) values ('cgrayl3@uiuc.edu', 'Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('jbrownl4@quantcast.com', 'Fentanyl Citrate');
insert into fooduser (Email, Food) values ('chudsonl5@infoseek.co.jp', 'PREMIER VALUE TOLNAFTATE ANTIFUNGAL');
insert into fooduser (Email, Food) values ('dgriffinl6@cam.ac.uk', 'Metformin Hydrochloride');
insert into fooduser (Email, Food) values ('lfullerl7@theguardian.com', 'Sore Throat Cherry');
insert into fooduser (Email, Food) values ('drileyl8@lulu.com', 'SKIN SUPPLIES FOR MEN');
insert into fooduser (Email, Food) values ('cphillipsl9@narod.ru', 'EROS RELAX');
insert into fooduser (Email, Food) values ('sgardnerla@twitter.com', 'Aquaphor Lip Repair and Protect');
insert into fooduser (Email, Food) values ('ebelllb@wunderground.com', 'EczeNil');
insert into fooduser (Email, Food) values ('djacksonlc@yellowpages.com', 'Allopurinol');
insert into fooduser (Email, Food) values ('bnguyenld@thetimes.co.uk', 'Ursodiol');
insert into fooduser (Email, Food) values ('bnicholsle@scientificamerican.com', 'Venlafaxine Hydrochloride');
insert into fooduser (Email, Food) values ('mmatthewslf@edublogs.org', 'NABUMETONE');
insert into fooduser (Email, Food) values ('rraylg@flickr.com', 'LBel');
insert into fooduser (Email, Food) values ('rsimslh@t.co', 'promethazine hydrochloride');
insert into fooduser (Email, Food) values ('claneli@networkadvertising.org', 'Clorazepate Dipotassium');
insert into fooduser (Email, Food) values ('dbankslj@ocn.ne.jp', 'Apis ex animale 6 Special Order');
insert into fooduser (Email, Food) values ('rcastillolk@weebly.com', 'REPAIRWEAR UPLIFTING FIRMING');
insert into fooduser (Email, Food) values ('drossll@yelp.com', 'HayFever Fighter');
insert into fooduser (Email, Food) values ('cjenkinslm@indiatimes.com', 'Miracle Foot Repair');
insert into fooduser (Email, Food) values ('eriveraln@wunderground.com', 'Natural Fiber Therapy');
insert into fooduser (Email, Food) values ('dfloreslo@go.com', 'Oxaliplatin');
insert into fooduser (Email, Food) values ('wraylp@about.com', 'RAZADYNE');
insert into fooduser (Email, Food) values ('rjoneslq@blogtalkradio.com', 'paclitaxel');
insert into fooduser (Email, Food) values ('dthompsonlr@opera.com', 'Pollens - Trees, Elm, Chinese Ulmus parvifolia');
insert into fooduser (Email, Food) values ('bcrawfordls@hud.gov', 'Meloxicam');
insert into fooduser (Email, Food) values ('jhowelllt@wired.com', 'Pamidronate Disodium');
insert into fooduser (Email, Food) values ('ajohnsonlu@hexun.com', 'Standardized Cat Hair');
insert into fooduser (Email, Food) values ('hrobinsonlv@facebook.com', 'Arterioforce');
insert into fooduser (Email, Food) values ('lchapmanlw@spotify.com', 'Surfak Stool Softener');
insert into fooduser (Email, Food) values ('bcunninghamlx@360.cn', 'Mefloquine Hydrochloride');
insert into fooduser (Email, Food) values ('lvasquezly@hc360.com', 'ALAVERT ALLERGY SINUS D-12');
insert into fooduser (Email, Food) values ('jruizlz@soup.io', 'Aspirin Free Headache PM');
insert into fooduser (Email, Food) values ('wmartinezm0@amazon.co.uk', 'Pioglitazone Hydrochloride');
insert into fooduser (Email, Food) values ('creyesm1@barnesandnoble.com', 'Cefazolin');
insert into fooduser (Email, Food) values ('rjacobsm2@arizona.edu', 'cold');
insert into fooduser (Email, Food) values ('aarmstrongm3@wired.com', 'OxyContin');
insert into fooduser (Email, Food) values ('fphillipsm4@epa.gov', 'amoxicillin and clavulanate potassium');
insert into fooduser (Email, Food) values ('jmedinam5@amazon.de', 'Chinese Elm Pollen');
insert into fooduser (Email, Food) values ('jfrazierm6@huffingtonpost.com', 'NEXIUM');
insert into fooduser (Email, Food) values ('sgarrettm7@newyorker.com', 'Minivelle');
insert into fooduser (Email, Food) values ('hsimpsonm8@devhub.com', 'CHILDRENS DIMETAPP COLD AND COUGH');
insert into fooduser (Email, Food) values ('rhicksm9@geocities.jp', 'Simvastatin');
insert into fooduser (Email, Food) values ('jwheelerma@instagram.com', 'SEROQUEL');
insert into fooduser (Email, Food) values ('mcollinsmb@woothemes.com', 'Cefuroxime');
insert into fooduser (Email, Food) values ('molsonmc@geocities.jp', 'Oxcarbazepine');
insert into fooduser (Email, Food) values ('kellismd@symantec.com', 'Beyond BB Perfecting Foundation Broad Spectrum SPF 15 Sunscreen');
insert into fooduser (Email, Food) values ('rharveyme@mashable.com', 'Tramadol Hydrochloride');
insert into fooduser (Email, Food) values ('kdanielsmf@alexa.com', 'MEDI-FIRST Ibuprofen');
insert into fooduser (Email, Food) values ('ljordanmg@mysql.com', 'Old Spice High Endurance');
insert into fooduser (Email, Food) values ('mpricemh@cbsnews.com', 'ERYTHROMYCIN Base Filmtab');
insert into fooduser (Email, Food) values ('jtaylormi@weebly.com', 'Lisinopril');
insert into fooduser (Email, Food) values ('mrosemj@sourceforge.net', 'Buxom Show Some Skin Weightless Foundation Broad Spectrum SPF 30');
insert into fooduser (Email, Food) values ('dgarzamk@hp.com', 'Nicotine polacrilex');
insert into fooduser (Email, Food) values ('ebakerml@tmall.com', 'LEADER LUBRICATING EYE DROPS');
insert into fooduser (Email, Food) values ('ewardmm@goo.ne.jp', 'Bionica Pain Relieving Gel');
insert into fooduser (Email, Food) values ('jwashingtonmn@shinystat.com', 'Olanzapine');
insert into fooduser (Email, Food) values ('dpetersmo@nba.com', 'Walgreens Aloe Vera');
insert into fooduser (Email, Food) values ('kcarrollmp@constantcontact.com', 'Trihexyphenidyl Hydrochloride');
insert into fooduser (Email, Food) values ('ddiazmq@state.gov', 'Fluorouracil');
insert into fooduser (Email, Food) values ('jcartermr@prlog.org', 'Meijer Suscreen SPF 8');
insert into fooduser (Email, Food) values ('bwagnerms@illinois.edu', 'Alprazolam');
insert into fooduser (Email, Food) values ('tjordanmt@technorati.com', 'Alendronate Sodium');
insert into fooduser (Email, Food) values ('eraymu@paypal.com', 'Arrid XX Extra Extra Dry');
insert into fooduser (Email, Food) values ('dberrymv@pcworld.com', 'Mexican Tea Pollen');
insert into fooduser (Email, Food) values ('ngrahammw@nsw.gov.au', 'Analgesic Balm');
insert into fooduser (Email, Food) values ('jturnermx@prlog.org', 'SODIUM SULFACETAMIDE - SULFUR CLEANSING PADS');
insert into fooduser (Email, Food) values ('jgibsonmy@intel.com', 'laura mercier tinted moisturizer Broad Spectrum SPF 20 Sunscreen Lightweight Flawless Coverage CAMEO');
insert into fooduser (Email, Food) values ('jrossmz@cocolog-nifty.com', 'END-ZIT');
insert into fooduser (Email, Food) values ('bgeorgen0@flickr.com', 'Sniffles');
insert into fooduser (Email, Food) values ('parnoldn1@twitpic.com', 'SHISEIDO THE MAKEUP LIFTING FOUNDATION');
insert into fooduser (Email, Food) values ('jjacksonn2@elpais.com', 'SunZone Family SPF 30');
insert into fooduser (Email, Food) values ('gstephensn3@yellowbook.com', 'Lisinopril');
insert into fooduser (Email, Food) values ('cjordann4@moonfruit.com', 'kids cough');
insert into fooduser (Email, Food) values ('jcoopern5@etsy.com', 'Bicalutamide');
insert into fooduser (Email, Food) values ('kdayn6@creativecommons.org', 'Ondansetron');
insert into fooduser (Email, Food) values ('pjohnstonn7@gmpg.org', 'Antiseptic Night Rinse');
insert into fooduser (Email, Food) values ('darmstrongn8@webmd.com', 'Pain Relief');
insert into fooduser (Email, Food) values ('rhowelln9@who.int', 'sunmark pain reliever');
insert into fooduser (Email, Food) values ('jhamiltonna@mlb.com', 'Parsley');
insert into fooduser (Email, Food) values ('bmurphynb@ucoz.com', 'Bio Oak');
insert into fooduser (Email, Food) values ('achapmannc@pen.io', 'Protonix');
insert into fooduser (Email, Food) values ('asimmonsnd@home.pl', 'Lisinopril');
insert into fooduser (Email, Food) values ('drobertsonne@google.es', 'KLEENEX Antibacterial Skin Cleanser');
insert into fooduser (Email, Food) values ('rwalkernf@slashdot.org', 'Ibuprofen');
insert into fooduser (Email, Food) values ('bgarrettng@acquirethisname.com', 'Acne and Blemish Target');
insert into fooduser (Email, Food) values ('bstanleynh@youtube.com', 'Prednisone');
insert into fooduser (Email, Food) values ('criceni@amazon.de', 'Etodolac');
insert into fooduser (Email, Food) values ('wberrynj@wiley.com', 'NEOMYCIN SULFATE, POLYMYXIN B SULFATE AND BACITRACIN ZINC');
insert into fooduser (Email, Food) values ('swoodnk@skyrock.com', 'Lexapro');
insert into fooduser (Email, Food) values ('enicholsnl@jiathis.com', 'butalbital, acetominophen and caffeine');
insert into fooduser (Email, Food) values ('djacksonnm@webnode.com', 'Sumatriptan Succinate');
insert into fooduser (Email, Food) values ('vwilsonnn@thetimes.co.uk', 'Mepivacaine');
insert into fooduser (Email, Food) values ('tperezno@freewebs.com', 'Viral Infection');
insert into fooduser (Email, Food) values ('kgarrettnp@ycombinator.com', 'AUGMENTIN');
insert into fooduser (Email, Food) values ('emasonnq@latimes.com', 'Atenolol');
insert into fooduser (Email, Food) values ('pbryantnr@nps.gov', 'Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('egomezns@newyorker.com', 'ENDOCET');
insert into fooduser (Email, Food) values ('sgeorgent@surveymonkey.com', 'HICKORY MIX, PIGNUT/SHAGBARK/SHELLBARK/WHITE POLLEN');
insert into fooduser (Email, Food) values ('jbutlernu@google.com', 'Metronidazole');
insert into fooduser (Email, Food) values ('sbryantnv@parallels.com', 'Simvastatin');
insert into fooduser (Email, Food) values ('hcastillonw@wikipedia.org', 'Osteodoron AM Special Formula');
insert into fooduser (Email, Food) values ('bstevensnx@reuters.com', 'Icy Hot Medicated No Mess Applicator');
insert into fooduser (Email, Food) values ('athompsonny@wp.com', 'Pepper Tree');
insert into fooduser (Email, Food) values ('rhansennz@canalblog.com', 'No7 Radiant Glow Foundation Sunscreen SPF 15 Buff');
insert into fooduser (Email, Food) values ('dpowello0@fema.gov', 'Diclofenac Potassium');
insert into fooduser (Email, Food) values ('lschmidto1@apache.org', 'ELIGARD');
insert into fooduser (Email, Food) values ('cstevenso2@sakura.ne.jp', 'Motion Sickness');
insert into fooduser (Email, Food) values ('jportero3@dropbox.com', 'Methyldopa');
insert into fooduser (Email, Food) values ('lbakero4@tmall.com', 'Oxygen');
insert into fooduser (Email, Food) values ('bwheelero5@umn.edu', 'Warfarin Sodium');
insert into fooduser (Email, Food) values ('kramoso6@ihg.com', 'Arnica Montana Kit Refill');
insert into fooduser (Email, Food) values ('rwalkero7@list-manage.com', 'Hydromet');
insert into fooduser (Email, Food) values ('bjacobso8@phpbb.com', 'ZOMIG');
insert into fooduser (Email, Food) values ('egreeno9@fc2.com', 'Hydralazine Hydrochloride');
insert into fooduser (Email, Food) values ('bandrewsoa@mozilla.org', 'METFORMIN HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('pclarkob@guardian.co.uk', 'Tamsulosin Hydrochloride');
insert into fooduser (Email, Food) values ('ksnyderoc@upenn.edu', 'CYPROHEPTADINE HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('nwheelerod@webeden.co.uk', 'Amlodipine besylate and benazepril hydrochloride');
insert into fooduser (Email, Food) values ('gwelchoe@wufoo.com', 'Hydrogen Peroxide');
insert into fooduser (Email, Food) values ('rbellof@instagram.com', 'Cold Remedy Gan Mao Ling');
insert into fooduser (Email, Food) values ('nromeroog@studiopress.com', 'Regio substantiae nigrae 6 Special Order');
insert into fooduser (Email, Food) values ('dhansenoh@yahoo.co.jp', 'Pepto-Bismol To Go');
insert into fooduser (Email, Food) values ('edavisoi@illinois.edu', 'Gerbil Epithelium');
insert into fooduser (Email, Food) values ('chuntoj@un.org', 'Lisinopril and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('jmurrayok@sfgate.com', 'Topcare Nite Time Cold and Flu');
insert into fooduser (Email, Food) values ('rfowlerol@discovery.com', 'Alcare Plus Foamed Antiseptic Handrub');
insert into fooduser (Email, Food) values ('rchapmanom@ox.ac.uk', 'PREPARATION H COOLING GEL');
insert into fooduser (Email, Food) values ('rharton@163.com', 'Fentanyl Citrate');
insert into fooduser (Email, Food) values ('jbanksoo@amazon.co.jp', 'TUMS');
insert into fooduser (Email, Food) values ('jcruzop@symantec.com', 'Degree Men');
insert into fooduser (Email, Food) values ('pleeoq@foxnews.com', 'Metronidazole');
insert into fooduser (Email, Food) values ('jwillisor@icio.us', 'ropinirole');
insert into fooduser (Email, Food) values ('jreyesos@facebook.com', 'Fluoxetine');
insert into fooduser (Email, Food) values ('clynchot@cnn.com', 'COUMADIN');
insert into fooduser (Email, Food) values ('dleeou@apple.com', 'SENSAI CELLULAR PERFORMANCE POWDER FOUNDATION');
insert into fooduser (Email, Food) values ('kpayneov@techcrunch.com', 'Temazepam');
insert into fooduser (Email, Food) values ('tbradleyow@yandex.ru', 'X-Out Wash-In Treatment');
insert into fooduser (Email, Food) values ('aknightox@hp.com', 'CVS PHARMACY');
insert into fooduser (Email, Food) values ('pcampbelloy@photobucket.com', 'ESIKA');
insert into fooduser (Email, Food) values ('sgardneroz@hubpages.com', 'DR. RECKEWEG R30 Atomare Beckeron');
insert into fooduser (Email, Food) values ('jjohnsonp0@accuweather.com', 'Head and Shoulders 2in1');
insert into fooduser (Email, Food) values ('hsnyderp1@myspace.com', 'Respen 40 (Number 70)');
insert into fooduser (Email, Food) values ('jmarshallp2@bloglines.com', 'Anti Diarrheal');
insert into fooduser (Email, Food) values ('mwestp3@apache.org', 'Vascular');
insert into fooduser (Email, Food) values ('jwagnerp4@angelfire.com', 'BENZTROPINE MESYLATE');
insert into fooduser (Email, Food) values ('cschmidtp5@bloglovin.com', 'Pleo Fort');
insert into fooduser (Email, Food) values ('jbrownp6@archive.org', 'BZK Alcohol');
insert into fooduser (Email, Food) values ('kreedp7@sitemeter.com', 'infants pain and fever');
insert into fooduser (Email, Food) values ('dgordonp8@europa.eu', 'TRAZODONE HYDROCHLORIDE');
insert into fooduser (Email, Food) values ('vbishopp9@eepurl.com', 'Allium Cepa Kit Refill');
insert into fooduser (Email, Food) values ('trussellpa@domainmarket.com', 'Lisinopril');
insert into fooduser (Email, Food) values ('scunninghampb@slideshare.net', 'Isopropyl Alcohol');
insert into fooduser (Email, Food) values ('bbrownpc@walmart.com', 'NITROGEN');
insert into fooduser (Email, Food) values ('aburkepd@senate.gov', 'equaline daytime cold');
insert into fooduser (Email, Food) values ('cwelchpe@deviantart.com', 'Bronchi');
insert into fooduser (Email, Food) values ('phansonpf@aol.com', 'Mirtazapine');
insert into fooduser (Email, Food) values ('jmccoypg@cdbaby.com', 'Cimicifuga-Homaccord');
insert into fooduser (Email, Food) values ('jtuckerph@cmu.edu', 'Diltiazem Hydrochloride');
insert into fooduser (Email, Food) values ('pwallacepi@guardian.co.uk', 'ANTISEPTIC HAND GEL');
insert into fooduser (Email, Food) values ('cpricepj@auda.org.au', 'Etodolac');
insert into fooduser (Email, Food) values ('dwelchpk@simplemachines.org', 'Leflunomide');
insert into fooduser (Email, Food) values ('jgarciapl@toplist.cz', 'RoC Multi Correxion');
insert into fooduser (Email, Food) values ('amorenopm@cisco.com', 'Petrochemical Detox');
insert into fooduser (Email, Food) values ('lthomaspn@photobucket.com', 'Degree');
insert into fooduser (Email, Food) values ('jricepo@google.es', '2 IN 1 POWDER MAKE-UP');
insert into fooduser (Email, Food) values ('amorenopp@163.com', 'Tinted Moisturizer SPF20');
insert into fooduser (Email, Food) values ('lhillpq@4shared.com', 'Prednisone');
insert into fooduser (Email, Food) values ('lmatthewspr@guardian.co.uk', 'Coppertone UltraGuard');
insert into fooduser (Email, Food) values ('ccookps@sina.com.cn', 'Albuterol Sulfate');
insert into fooduser (Email, Food) values ('kgutierrezpt@google.fr', 'Aquavit Etheric Energizer');
insert into fooduser (Email, Food) values ('ehawkinspu@blogger.com', 'blackberry vanilla hand sanitizer');
insert into fooduser (Email, Food) values ('drichardsonpv@moonfruit.com', 'LES BEIGES');
insert into fooduser (Email, Food) values ('dharveypw@shop-pro.jp', '3LAB PERFECT BB SPF 40 Broad Spectrum 03');
insert into fooduser (Email, Food) values ('agardnerpx@google.com.br', 'Good Neighbor Pharmacy');
insert into fooduser (Email, Food) values ('ehartpy@indiegogo.com', 'Royal Antibacterial Orange Berry Hand Cleanse');
insert into fooduser (Email, Food) values ('esimpsonpz@cnbc.com', 'Humulin 70/30');
insert into fooduser (Email, Food) values ('chansonq0@bloglovin.com', 'Hydroxyzine Hydrochloride');
insert into fooduser (Email, Food) values ('ahartq1@taobao.com', 'Musculus deltoideus comp. 8 Special Order');
insert into fooduser (Email, Food) values ('cgarciaq2@google.fr', 'Ready Foundation');
insert into fooduser (Email, Food) values ('nolsonq3@arizona.edu', 'LBEL COULEUR LUXE AMPLIFIER XP');
insert into fooduser (Email, Food) values ('wlarsonq4@netlog.com', 'Norepinephrine');
insert into fooduser (Email, Food) values ('jmorrisonq5@meetup.com', 'Argatroban');
insert into fooduser (Email, Food) values ('ehartq6@constantcontact.com', 'Wal Four');
insert into fooduser (Email, Food) values ('lbakerq7@cyberchimps.com', 'fexofenadine hydrochloride');
insert into fooduser (Email, Food) values ('kcooperq8@ft.com', 'Opana');
insert into fooduser (Email, Food) values ('cstevensq9@sbwire.com', 'Bupropion Hydrochloride');
insert into fooduser (Email, Food) values ('shartqa@umich.edu', 'Hydroxyzine Pamoate');
insert into fooduser (Email, Food) values ('jharrisqb@hhs.gov', 'Neomycin Polymyxin B Sulfates and Dexamethasone');
insert into fooduser (Email, Food) values ('bjordanqc@instagram.com', 'CEFAZOLIN');
insert into fooduser (Email, Food) values ('mcoleqd@last.fm', 'Morphine Sulfate');
insert into fooduser (Email, Food) values ('staylorqe@wikispaces.com', 'PURELL Advanced Hand Sanitizer SpongeBob Splash');
insert into fooduser (Email, Food) values ('agonzalesqf@furl.net', 'Pindolol');
insert into fooduser (Email, Food) values ('apattersonqg@cbsnews.com', 'Inflammation');
insert into fooduser (Email, Food) values ('bandrewsqh@google.ca', 'benzoyl peroxide');
insert into fooduser (Email, Food) values ('jpattersonqi@ed.gov', 'CEFADROXIL');
insert into fooduser (Email, Food) values ('mwestqj@chicagotribune.com', 'Lysol');
insert into fooduser (Email, Food) values ('wnelsonqk@ifeng.com', 'PLANTAGO LANCEOLATA POLLEN');
insert into fooduser (Email, Food) values ('jmcdonaldql@ehow.com', 'Coly-Mycin S');
insert into fooduser (Email, Food) values ('jruizqm@gmpg.org', 'Theophylline');
insert into fooduser (Email, Food) values ('smillerqn@elegantthemes.com', 'Denti-Care Denti-Rinse');
insert into fooduser (Email, Food) values ('falvarezqo@patch.com', 'Aromafields Tiger Lily Scented Anti-Bacterial Hand');
insert into fooduser (Email, Food) values ('dphillipsqp@nih.gov', 'Black Olive');
insert into fooduser (Email, Food) values ('fthomasqq@umich.edu', 'Lansoprazole');
insert into fooduser (Email, Food) values ('scarterqr@nydailynews.com', 'Neutrogena T/Gel Therapeutic');
insert into fooduser (Email, Food) values ('pmorenoqs@msu.edu', 'Aller-Detox Caffeine');
insert into fooduser (Email, Food) values ('sfoxqt@cbslocal.com', 'SUN PROTECTION BODY SUNSCREEN BROAD SPECTRUM SPF 30');
insert into fooduser (Email, Food) values ('hrosequ@howstuffworks.com', 'aspirin');
insert into fooduser (Email, Food) values ('tthompsonqv@earthlink.net', 'Ramipril');
insert into fooduser (Email, Food) values ('rrileyqw@4shared.com', 'Menopause');
insert into fooduser (Email, Food) values ('mgilbertqx@hc360.com', 'SPF 18 SUPER SENSITIVE SUNSCREEN');
insert into fooduser (Email, Food) values ('mrileyqy@histats.com', 'Menopur');
insert into fooduser (Email, Food) values ('rhenryqz@dot.gov', 'lisinopril');
insert into fooduser (Email, Food) values ('dhicksr0@ca.gov', 'Naproxen');
insert into fooduser (Email, Food) values ('hcruzr1@constantcontact.com', 'Warfarin Sodium');
insert into fooduser (Email, Food) values ('bhowellr2@a8.net', 'Russian Olive');
insert into fooduser (Email, Food) values ('dtorresr3@etsy.com', 'Hand Sanitizer');
insert into fooduser (Email, Food) values ('gmorganr4@google.pl', 'Topiramate');
insert into fooduser (Email, Food) values ('bmitchellr5@bizjournals.com', 'Quetiapine fumarate');
insert into fooduser (Email, Food) values ('dgrahamr6@bloomberg.com', 'Doc Q Lace');
insert into fooduser (Email, Food) values ('mgardnerr7@webs.com', 'Rhodotorula mucilaginosa');
insert into fooduser (Email, Food) values ('rreidr8@ox.ac.uk', 'MakeSense');
insert into fooduser (Email, Food) values ('mevansr9@huffingtonpost.com', 'Ibuprofen');
insert into fooduser (Email, Food) values ('jruizra@bloglines.com', 'Dermablend Professional SkinPerfector Blemish and Oil Clearing Primer');
insert into fooduser (Email, Food) values ('aevansrb@vistaprint.com', 'Warm Deep Matte');
insert into fooduser (Email, Food) values ('mwarrenrc@thetimes.co.uk', 'Pravastatin sodium');
insert into fooduser (Email, Food) values ('wwelchrd@moonfruit.com', 'Terazosin hydrochloride');
insert into fooduser (Email, Food) values ('lruizre@gov.uk', 'Low Back Pain');
insert into fooduser (Email, Food) values ('towensrf@spotify.com', 'OB Towelette');
insert into fooduser (Email, Food) values ('bhansenrg@ow.ly', 'XOXO Kit');
insert into fooduser (Email, Food) values ('rwestrh@uiuc.edu', 'Hydrogen Peroxide');
insert into fooduser (Email, Food) values ('awheelerri@nih.gov', 'Acetaminophen PM Rapid Release');
insert into fooduser (Email, Food) values ('jgonzalesrj@dyndns.org', 'Zicam Cold Remedy Kids Soft Chews');
insert into fooduser (Email, Food) values ('pbellrk@rambler.ru', 'Quinapril');
insert into fooduser (Email, Food) values ('lsimmonsrl@flavors.me', 'BABOR HSR Lifting Eye Cream');
insert into fooduser (Email, Food) values ('jcarrollrm@dailymail.co.uk', 'Neutrogena Healthy Skin Compact Makeup');
insert into fooduser (Email, Food) values ('tjamesrn@ning.com', 'Benazepril Hydrochloride and Hydrochlorothiazide');
insert into fooduser (Email, Food) values ('dwilsonro@prnewswire.com', 'CareOne Daytime Cold Flu Relief');
insert into fooduser (Email, Food) values ('sarnoldrp@utexas.edu', 'Zosyn');
insert into fooduser (Email, Food) values ('tbryantrq@archive.org', 'Lancome Paris High Resolution Refill 3X Triple Action Renewal Anti Wrinkle Broad Spectrum SPF 15 Sunscreen');
insert into fooduser (Email, Food) values ('rtuckerrr@state.tx.us', 'Equate Acne Treatment Body Pads');
