create table fooduser (
	Email VARCHAR(255),
	Food VARCHAR(255),
	InputTime datetime
);
insert into fooduser (Email, Food, InputTime) values ('sperez0@ebay.co.uk', 'Whooper', '3:03 PM');
insert into fooduser (Email, Food, InputTime) values ('jpierce3@weather.com', 'Big Mac', '3:56 PM');
insert into fooduser (Email, Food, InputTime) values ('dwilliamson1@vimeo.com', 'Whooper', '2:05 PM');
insert into fooduser (Email, Food, InputTime) values ('jlewis2@phoca.cz', 'Dave''s Single from Wendy''s', '5:46 PM');
insert into fooduser (Email, Food, InputTime) values ('kmorris4@ehow.com', 'Dave''s Single from Wendy''s', '4:22 AM');
insert into fooduser (Email, Food, InputTime) values ('rlawrence5@cyberchimps.com', 'Dave''s Single from Wendy''s', '2:03 PM');
insert into fooduser (Email, Food, InputTime) values ('aryan6@cbc.ca', 'Big Mac', '6:12 AM');
insert into fooduser (Email, Food, InputTime) values ('akelly7@ask.com', 'Big Mac', '8:10 PM');
insert into fooduser (Email, Food, InputTime) values ('jlong8@shinystat.com', 'Dave''s Single from Wendy''s', '3:45 AM');
insert into fooduser (Email, Food, InputTime) values ('pwagner9@pagesperso-orange.fr', 'Dave''s Single from Wendy''s', '1:28 PM');
insert into fooduser (Email, Food, InputTime) values ('ijacobsa@cnbc.com', 'Whooper', '4:22 PM');
insert into fooduser (Email, Food, InputTime) values ('ethomasb@eventbrite.com', 'Big Mac', '6:10 AM');
insert into fooduser (Email, Food, InputTime) values ('tporterc@cornell.edu', 'Big Mac', '3:10 AM');
insert into fooduser (Email, Food, InputTime) values ('jsimpsond@php.net', 'Big Mac', '8:59 PM');
insert into fooduser (Email, Food, InputTime) values ('hreynoldse@github.io', 'Dave''s Single from Wendy''s', '9:37 AM');
insert into fooduser (Email, Food, InputTime) values ('rcunninghamf@cbc.ca', 'Dave''s Single from Wendy''s', '2:35 AM');
insert into fooduser (Email, Food, InputTime) values ('kfisherg@live.com', 'Whooper', '1:34 PM');
insert into fooduser (Email, Food, InputTime) values ('hholmesh@goo.ne.jp', 'Big Mac', '8:42 AM');
insert into fooduser (Email, Food, InputTime) values ('lwesti@indiatimes.com', 'Big Mac', '2:01 PM');
insert into fooduser (Email, Food, InputTime) values ('dbishopj@economist.com', 'Dave''s Single from Wendy''s', '12:06 PM');
insert into fooduser (Email, Food, InputTime) values ('lwalkerk@networkadvertising.org', 'Dave''s Single from Wendy''s', '11:29 PM');
insert into fooduser (Email, Food, InputTime) values ('acolemanl@berkeley.edu', 'Whooper', '11:28 AM');
insert into fooduser (Email, Food, InputTime) values ('cbellm@huffingtonpost.com', 'Big Mac', '11:44 AM');
insert into fooduser (Email, Food, InputTime) values ('hharpern@merriam-webster.com', 'Whooper', '12:13 PM');
insert into fooduser (Email, Food, InputTime) values ('spierceo@ucsd.edu', 'Big Mac', '6:07 PM');
insert into fooduser (Email, Food, InputTime) values ('jgutierrezp@cnn.com', 'Whooper', '12:32 PM');
insert into fooduser (Email, Food, InputTime) values ('hlaneq@blog.com', 'Whooper', '1:22 AM');
insert into fooduser (Email, Food, InputTime) values ('gsimpsonr@ca.gov', 'Big Mac', '11:38 PM');
insert into fooduser (Email, Food, InputTime) values ('bandersons@cyberchimps.com', 'Dave''s Single from Wendy''s', '11:03 AM');
insert into fooduser (Email, Food, InputTime) values ('knelsont@wunderground.com', 'Dave''s Single from Wendy''s', '10:58 AM');
insert into fooduser (Email, Food, InputTime) values ('dshawu@arizona.edu', 'Dave''s Single from Wendy''s', '4:54 PM');
insert into fooduser (Email, Food, InputTime) values ('wblackv@cbsnews.com', 'Dave''s Single from Wendy''s', '1:59 AM');
insert into fooduser (Email, Food, InputTime) values ('jromerow@comsenz.com', 'Whooper', '2:45 PM');
insert into fooduser (Email, Food, InputTime) values ('dhudsonx@tumblr.com', 'Dave''s Single from Wendy''s', '10:55 AM');
insert into fooduser (Email, Food, InputTime) values ('mcarpentery@bloomberg.com', 'Whooper', '9:24 PM');
insert into fooduser (Email, Food, InputTime) values ('agonzalezz@discuz.net', 'Big Mac', '4:45 AM');
insert into fooduser (Email, Food, InputTime) values ('mrose10@gmpg.org', 'Big Mac', '7:30 PM');
insert into fooduser (Email, Food, InputTime) values ('ffrazier11@livejournal.com', 'Dave''s Single from Wendy''s', '7:50 AM');
insert into fooduser (Email, Food, InputTime) values ('sphillips12@intel.com', 'Big Mac', '6:28 AM');
insert into fooduser (Email, Food, InputTime) values ('tstevens13@scientificamerican.com', 'Whooper', '12:24 PM');
insert into fooduser (Email, Food, InputTime) values ('croberts14@google.it', 'Dave''s Single from Wendy''s', '5:10 AM');
insert into fooduser (Email, Food, InputTime) values ('nbishop15@lulu.com', 'Whooper', '7:12 AM');
insert into fooduser (Email, Food, InputTime) values ('jprice16@yale.edu', 'Dave''s Single from Wendy''s', '3:11 PM');
insert into fooduser (Email, Food, InputTime) values ('ereyes17@yahoo.co.jp', 'Whooper', '10:18 AM');
insert into fooduser (Email, Food, InputTime) values ('swelch18@sbwire.com', 'Dave''s Single from Wendy''s', '1:25 PM');
insert into fooduser (Email, Food, InputTime) values ('rbryant19@gravatar.com', 'Dave''s Single from Wendy''s', '7:13 PM');
insert into fooduser (Email, Food, InputTime) values ('ljacobs1a@mozilla.com', 'Whooper', '9:07 AM');
insert into fooduser (Email, Food, InputTime) values ('jwillis1b@lulu.com', 'Whooper', '11:38 PM');
insert into fooduser (Email, Food, InputTime) values ('bsmith1c@ed.gov', 'Big Mac', '9:58 AM');
insert into fooduser (Email, Food, InputTime) values ('eknight1d@latimes.com', 'Dave''s Single from Wendy''s', '12:22 AM');
insert into fooduser (Email, Food, InputTime) values ('sjohnson1e@opera.com', 'Big Mac', '1:18 AM');
insert into fooduser (Email, Food, InputTime) values ('hking1f@baidu.com', 'Big Mac', '12:35 PM');
insert into fooduser (Email, Food, InputTime) values ('tyoung1g@wikispaces.com', 'Dave''s Single from Wendy''s', '8:05 AM');
insert into fooduser (Email, Food, InputTime) values ('mweaver1h@naver.com', 'Big Mac', '7:33 PM');
insert into fooduser (Email, Food, InputTime) values ('daustin1i@huffingtonpost.com', 'Big Mac', '9:25 AM');
insert into fooduser (Email, Food, InputTime) values ('balexander1j@1688.com', 'Dave''s Single from Wendy''s', '12:32 AM');
insert into fooduser (Email, Food, InputTime) values ('jalexander1k@mayoclinic.com', 'Dave''s Single from Wendy''s', '6:34 PM');
insert into fooduser (Email, Food, InputTime) values ('dcoleman1l@csmonitor.com', 'Dave''s Single from Wendy''s', '10:27 PM');
insert into fooduser (Email, Food, InputTime) values ('mtucker1m@com.com', 'Dave''s Single from Wendy''s', '12:45 AM');
insert into fooduser (Email, Food, InputTime) values ('kking1n@go.com', 'Whooper', '10:01 PM');
insert into fooduser (Email, Food, InputTime) values ('pfuller1o@meetup.com', 'Dave''s Single from Wendy''s', '10:30 PM');
insert into fooduser (Email, Food, InputTime) values ('ajohnston1p@barnesandnoble.com', 'Dave''s Single from Wendy''s', '1:17 PM');
insert into fooduser (Email, Food, InputTime) values ('bwells1q@storify.com', 'Dave''s Single from Wendy''s', '5:58 PM');
insert into fooduser (Email, Food, InputTime) values ('pgardner1r@amazon.co.jp', 'Big Mac', '7:01 AM');
insert into fooduser (Email, Food, InputTime) values ('jburton1s@google.co.uk', 'Big Mac', '6:17 AM');
insert into fooduser (Email, Food, InputTime) values ('pbarnes1t@globo.com', 'Big Mac', '12:52 AM');
insert into fooduser (Email, Food, InputTime) values ('lcunningham1u@imdb.com', 'Big Mac', '12:07 PM');
insert into fooduser (Email, Food, InputTime) values ('mkelly1v@soup.io', 'Whooper', '2:00 AM');
insert into fooduser (Email, Food, InputTime) values ('sporter1w@slate.com', 'Whooper', '9:26 PM');
insert into fooduser (Email, Food, InputTime) values ('cray1x@nbcnews.com', 'Whooper', '6:52 PM');
insert into fooduser (Email, Food, InputTime) values ('egarcia1y@senate.gov', 'Whooper', '8:52 PM');
insert into fooduser (Email, Food, InputTime) values ('proberts1z@cafepress.com', 'Big Mac', '5:26 AM');
insert into fooduser (Email, Food, InputTime) values ('mcook20@angelfire.com', 'Whooper', '12:50 PM');
insert into fooduser (Email, Food, InputTime) values ('ecarr21@e-recht24.de', 'Dave''s Single from Wendy''s', '4:05 PM');
insert into fooduser (Email, Food, InputTime) values ('croberts22@google.co.uk', 'Whooper', '11:47 PM');
insert into fooduser (Email, Food, InputTime) values ('sberry23@soundcloud.com', 'Dave''s Single from Wendy''s', '9:59 PM');
insert into fooduser (Email, Food, InputTime) values ('lperkins24@last.fm', 'Big Mac', '6:03 AM');
insert into fooduser (Email, Food, InputTime) values ('jgray25@reference.com', 'Whooper', '3:29 PM');
insert into fooduser (Email, Food, InputTime) values ('bhowell26@dmoz.org', 'Big Mac', '4:56 AM');
insert into fooduser (Email, Food, InputTime) values ('awagner27@over-blog.com', 'Dave''s Single from Wendy''s', '2:13 PM');
insert into fooduser (Email, Food, InputTime) values ('jpeterson28@admin.ch', 'Whooper', '2:53 PM');
insert into fooduser (Email, Food, InputTime) values ('asanchez29@people.com.cn', 'Whooper', '11:58 PM');
insert into fooduser (Email, Food, InputTime) values ('tweaver2a@globo.com', 'Big Mac', '10:45 AM');
insert into fooduser (Email, Food, InputTime) values ('lcarter2b@4shared.com', 'Big Mac', '7:04 AM');
insert into fooduser (Email, Food, InputTime) values ('hboyd2c@mac.com', 'Whooper', '3:10 PM');
insert into fooduser (Email, Food, InputTime) values ('jryan2d@uol.com.br', 'Whooper', '11:28 PM');
insert into fooduser (Email, Food, InputTime) values ('ereynolds2e@ocn.ne.jp', 'Whooper', '8:47 PM');
insert into fooduser (Email, Food, InputTime) values ('jburns2f@odnoklassniki.ru', 'Big Mac', '2:41 AM');
insert into fooduser (Email, Food, InputTime) values ('jdixon2g@mozilla.com', 'Big Mac', '11:52 PM');
insert into fooduser (Email, Food, InputTime) values ('aperkins2h@multiply.com', 'Whooper', '4:47 PM');
insert into fooduser (Email, Food, InputTime) values ('rjones2i@reuters.com', 'Big Mac', '2:55 AM');
insert into fooduser (Email, Food, InputTime) values ('gharrison2j@nba.com', 'Whooper', '10:22 AM');
insert into fooduser (Email, Food, InputTime) values ('wowens2k@1688.com', 'Big Mac', '1:23 AM');
insert into fooduser (Email, Food, InputTime) values ('lschmidt2l@google.de', 'Dave''s Single from Wendy''s', '9:57 AM');
insert into fooduser (Email, Food, InputTime) values ('abennett2m@biglobe.ne.jp', 'Whooper', '11:34 AM');
insert into fooduser (Email, Food, InputTime) values ('pdunn2n@cam.ac.uk', 'Whooper', '2:38 PM');
insert into fooduser (Email, Food, InputTime) values ('bbailey2o@fema.gov', 'Big Mac', '10:37 AM');
insert into fooduser (Email, Food, InputTime) values ('lhenry2p@facebook.com', 'Whooper', '4:53 PM');
insert into fooduser (Email, Food, InputTime) values ('kspencer2q@360.cn', 'Big Mac', '12:27 PM');
insert into fooduser (Email, Food, InputTime) values ('dgreen2r@google.com.au', 'Big Mac', '8:02 AM');
insert into fooduser (Email, Food, InputTime) values ('sduncan2s@artisteer.com', 'Whooper', '12:50 PM');
insert into fooduser (Email, Food, InputTime) values ('cruiz2t@simplemachines.org', 'Dave''s Single from Wendy''s', '7:53 AM');
insert into fooduser (Email, Food, InputTime) values ('dvasquez2u@nymag.com', 'Big Mac', '11:48 AM');
insert into fooduser (Email, Food, InputTime) values ('wreynolds2v@etsy.com', 'Big Mac', '4:10 PM');
insert into fooduser (Email, Food, InputTime) values ('aclark2w@constantcontact.com', 'Whooper', '7:48 AM');
insert into fooduser (Email, Food, InputTime) values ('aromero2x@wufoo.com', 'Dave''s Single from Wendy''s', '4:09 AM');
insert into fooduser (Email, Food, InputTime) values ('mfowler2y@msu.edu', 'Big Mac', '9:35 PM');
insert into fooduser (Email, Food, InputTime) values ('mryan2z@spotify.com', 'Dave''s Single from Wendy''s', '6:15 AM');
insert into fooduser (Email, Food, InputTime) values ('jfernandez30@t-online.de', 'Dave''s Single from Wendy''s', '9:02 AM');
insert into fooduser (Email, Food, InputTime) values ('dlynch31@xrea.com', 'Big Mac', '10:47 PM');
insert into fooduser (Email, Food, InputTime) values ('bmartinez32@wp.com', 'Dave''s Single from Wendy''s', '9:35 PM');
insert into fooduser (Email, Food, InputTime) values ('wwebb33@symantec.com', 'Dave''s Single from Wendy''s', '9:58 AM');
insert into fooduser (Email, Food, InputTime) values ('randrews34@nps.gov', 'Big Mac', '6:22 AM');
insert into fooduser (Email, Food, InputTime) values ('bellis35@census.gov', 'Whooper', '12:52 AM');
insert into fooduser (Email, Food, InputTime) values ('aperez36@google.cn', 'Whooper', '10:13 PM');
insert into fooduser (Email, Food, InputTime) values ('mferguson37@imgur.com', 'Dave''s Single from Wendy''s', '4:50 AM');
insert into fooduser (Email, Food, InputTime) values ('bcooper38@stumbleupon.com', 'Big Mac', '10:43 AM');
insert into fooduser (Email, Food, InputTime) values ('cbell39@last.fm', 'Whooper', '3:58 AM');
insert into fooduser (Email, Food, InputTime) values ('poliver3a@ted.com', 'Whooper', '2:18 AM');
insert into fooduser (Email, Food, InputTime) values ('tbennett3b@slashdot.org', 'Whooper', '2:58 PM');
insert into fooduser (Email, Food, InputTime) values ('vkim3c@gmpg.org', 'Dave''s Single from Wendy''s', '5:56 AM');
insert into fooduser (Email, Food, InputTime) values ('dweaver3d@apple.com', 'Big Mac', '3:39 PM');
insert into fooduser (Email, Food, InputTime) values ('kflores3e@cloudflare.com', 'Big Mac', '11:12 AM');
insert into fooduser (Email, Food, InputTime) values ('smarshall3f@techcrunch.com', 'Dave''s Single from Wendy''s', '10:43 PM');
insert into fooduser (Email, Food, InputTime) values ('jdixon3g@webeden.co.uk', 'Whooper', '4:59 PM');
insert into fooduser (Email, Food, InputTime) values ('kjacobs3h@usnews.com', 'Whooper', '10:25 PM');
insert into fooduser (Email, Food, InputTime) values ('pperez3i@ovh.net', 'Big Mac', '3:39 AM');
insert into fooduser (Email, Food, InputTime) values ('smatthews3j@berkeley.edu', 'Dave''s Single from Wendy''s', '5:59 PM');
insert into fooduser (Email, Food, InputTime) values ('bjohnston3k@cdbaby.com', 'Big Mac', '5:21 AM');
insert into fooduser (Email, Food, InputTime) values ('jcarpenter3l@slashdot.org', 'Whooper', '3:40 PM');
insert into fooduser (Email, Food, InputTime) values ('cduncan3m@geocities.jp', 'Big Mac', '1:29 AM');
insert into fooduser (Email, Food, InputTime) values ('bbowman3n@surveymonkey.com', 'Whooper', '7:24 AM');
insert into fooduser (Email, Food, InputTime) values ('jkelly3o@twitpic.com', 'Whooper', '3:45 PM');
insert into fooduser (Email, Food, InputTime) values ('charvey3p@chicagotribune.com', 'Big Mac', '9:24 AM');
insert into fooduser (Email, Food, InputTime) values ('jscott3q@google.de', 'Dave''s Single from Wendy''s', '12:55 AM');
insert into fooduser (Email, Food, InputTime) values ('lsanders3r@slideshare.net', 'Whooper', '7:17 PM');
insert into fooduser (Email, Food, InputTime) values ('tblack3s@nbcnews.com', 'Dave''s Single from Wendy''s', '5:36 PM');
insert into fooduser (Email, Food, InputTime) values ('akelly3t@mayoclinic.com', 'Whooper', '1:22 PM');
insert into fooduser (Email, Food, InputTime) values ('cgriffin3u@gov.uk', 'Whooper', '2:11 PM');
insert into fooduser (Email, Food, InputTime) values ('hthompson3v@macromedia.com', 'Whooper', '11:36 AM');
insert into fooduser (Email, Food, InputTime) values ('hspencer3w@tmall.com', 'Whooper', '12:01 AM');
insert into fooduser (Email, Food, InputTime) values ('sortiz3x@vistaprint.com', 'Dave''s Single from Wendy''s', '8:52 AM');
insert into fooduser (Email, Food, InputTime) values ('brichards3y@alexa.com', 'Big Mac', '6:33 AM');
insert into fooduser (Email, Food, InputTime) values ('jadams3z@tripadvisor.com', 'Dave''s Single from Wendy''s', '8:38 AM');
insert into fooduser (Email, Food, InputTime) values ('shicks40@seesaa.net', 'Big Mac', '11:18 AM');
insert into fooduser (Email, Food, InputTime) values ('djohnson41@de.vu', 'Big Mac', '7:04 PM');
insert into fooduser (Email, Food, InputTime) values ('kelliott42@slideshare.net', 'Whooper', '12:42 AM');
insert into fooduser (Email, Food, InputTime) values ('mrodriguez43@topsy.com', 'Whooper', '4:34 PM');
insert into fooduser (Email, Food, InputTime) values ('aharris44@pen.io', 'Dave''s Single from Wendy''s', '8:52 AM');
insert into fooduser (Email, Food, InputTime) values ('rhansen45@networksolutions.com', 'Dave''s Single from Wendy''s', '7:38 PM');
insert into fooduser (Email, Food, InputTime) values ('mortiz46@theglobeandmail.com', 'Whooper', '5:12 AM');
insert into fooduser (Email, Food, InputTime) values ('bmarshall47@purevolume.com', 'Whooper', '4:30 PM');
insert into fooduser (Email, Food, InputTime) values ('mtaylor48@uol.com.br', 'Big Mac', '9:41 AM');
insert into fooduser (Email, Food, InputTime) values ('kbaker49@businesswire.com', 'Whooper', '9:19 AM');
insert into fooduser (Email, Food, InputTime) values ('sgardner4a@macromedia.com', 'Dave''s Single from Wendy''s', '5:56 AM');
insert into fooduser (Email, Food, InputTime) values ('ccole4b@fda.gov', 'Whooper', '2:32 AM');
insert into fooduser (Email, Food, InputTime) values ('abryant4c@mediafire.com', 'Big Mac', '6:26 PM');
insert into fooduser (Email, Food, InputTime) values ('cromero4d@chron.com', 'Dave''s Single from Wendy''s', '11:53 PM');
insert into fooduser (Email, Food, InputTime) values ('jgarza4e@1688.com', 'Dave''s Single from Wendy''s', '11:28 AM');
insert into fooduser (Email, Food, InputTime) values ('ajames4f@intel.com', 'Big Mac', '9:23 PM');
insert into fooduser (Email, Food, InputTime) values ('mrobertson4g@soundcloud.com', 'Whooper', '2:58 PM');
insert into fooduser (Email, Food, InputTime) values ('tcastillo4h@ft.com', 'Dave''s Single from Wendy''s', '7:12 AM');
insert into fooduser (Email, Food, InputTime) values ('jmurphy4i@sina.com.cn', 'Dave''s Single from Wendy''s', '2:46 PM');
insert into fooduser (Email, Food, InputTime) values ('jbishop4j@thetimes.co.uk', 'Big Mac', '12:18 PM');
insert into fooduser (Email, Food, InputTime) values ('jbailey4k@fotki.com', 'Big Mac', '7:30 AM');
insert into fooduser (Email, Food, InputTime) values ('jjackson4l@smugmug.com', 'Whooper', '5:07 AM');
insert into fooduser (Email, Food, InputTime) values ('ashaw4m@nydailynews.com', 'Big Mac', '8:51 AM');
insert into fooduser (Email, Food, InputTime) values ('bgutierrez4n@yandex.ru', 'Whooper', '7:07 PM');
insert into fooduser (Email, Food, InputTime) values ('tmorrison4o@thetimes.co.uk', 'Big Mac', '2:14 AM');
insert into fooduser (Email, Food, InputTime) values ('lgibson4p@si.edu', 'Whooper', '12:14 AM');
insert into fooduser (Email, Food, InputTime) values ('dmccoy4q@bandcamp.com', 'Big Mac', '4:51 AM');
insert into fooduser (Email, Food, InputTime) values ('jarmstrong4r@eepurl.com', 'Whooper', '5:35 PM');
insert into fooduser (Email, Food, InputTime) values ('mwarren4s@howstuffworks.com', 'Dave''s Single from Wendy''s', '7:24 AM');
insert into fooduser (Email, Food, InputTime) values ('mwright4t@boston.com', 'Whooper', '9:27 PM');
insert into fooduser (Email, Food, InputTime) values ('vharrison4u@nationalgeographic.com', 'Dave''s Single from Wendy''s', '1:21 PM');
insert into fooduser (Email, Food, InputTime) values ('mandrews4v@mozilla.com', 'Whooper', '11:56 PM');
insert into fooduser (Email, Food, InputTime) values ('wgarcia4w@eepurl.com', 'Whooper', '7:51 PM');
insert into fooduser (Email, Food, InputTime) values ('glawrence4x@merriam-webster.com', 'Whooper', '6:51 PM');
insert into fooduser (Email, Food, InputTime) values ('mmcdonald4y@kickstarter.com', 'Big Mac', '8:46 PM');
insert into fooduser (Email, Food, InputTime) values ('ccarpenter4z@parallels.com', 'Big Mac', '8:18 PM');
insert into fooduser (Email, Food, InputTime) values ('bmiller50@narod.ru', 'Whooper', '12:07 AM');
insert into fooduser (Email, Food, InputTime) values ('jstephens51@qq.com', 'Dave''s Single from Wendy''s', '1:18 AM');
insert into fooduser (Email, Food, InputTime) values ('ccollins52@gizmodo.com', 'Whooper', '2:02 AM');
insert into fooduser (Email, Food, InputTime) values ('dhowell53@answers.com', 'Big Mac', '3:51 AM');
insert into fooduser (Email, Food, InputTime) values ('gsimpson54@wired.com', 'Big Mac', '12:48 PM');
insert into fooduser (Email, Food, InputTime) values ('dwarren55@dedecms.com', 'Whooper', '5:47 PM');
insert into fooduser (Email, Food, InputTime) values ('crussell56@liveinternet.ru', 'Dave''s Single from Wendy''s', '7:57 AM');
insert into fooduser (Email, Food, InputTime) values ('jdean57@wikipedia.org', 'Dave''s Single from Wendy''s', '8:56 AM');
insert into fooduser (Email, Food, InputTime) values ('pmartin58@dion.ne.jp', 'Whooper', '6:49 PM');
insert into fooduser (Email, Food, InputTime) values ('thunt59@chron.com', 'Dave''s Single from Wendy''s', '5:21 PM');
insert into fooduser (Email, Food, InputTime) values ('kowens5a@reverbnation.com', 'Whooper', '1:05 AM');
insert into fooduser (Email, Food, InputTime) values ('kmorales5b@theatlantic.com', 'Whooper', '7:14 AM');
insert into fooduser (Email, Food, InputTime) values ('swarren5c@4shared.com', 'Dave''s Single from Wendy''s', '11:50 AM');
insert into fooduser (Email, Food, InputTime) values ('darnold5d@pinterest.com', 'Dave''s Single from Wendy''s', '4:04 AM');
insert into fooduser (Email, Food, InputTime) values ('etucker5e@delicious.com', 'Big Mac', '12:22 PM');
insert into fooduser (Email, Food, InputTime) values ('vrose5f@nasa.gov', 'Big Mac', '6:02 PM');
insert into fooduser (Email, Food, InputTime) values ('dbradley5g@auda.org.au', 'Whooper', '12:01 AM');
insert into fooduser (Email, Food, InputTime) values ('shanson5h@w3.org', 'Whooper', '12:31 PM');
insert into fooduser (Email, Food, InputTime) values ('lblack5i@cnn.com', 'Dave''s Single from Wendy''s', '11:12 AM');
insert into fooduser (Email, Food, InputTime) values ('wreyes5j@cmu.edu', 'Big Mac', '10:27 AM');
