INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('﻿category', 'calories');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Honey Mustard Sauce', '60');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southwest Crispy Chicken McWrap', '669');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry, with Rolo, snack size', '510');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Low-Fat Family Recipe Italian Dressing', '50');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Crispy Chicken & Bacon McWrap', '640');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Low-Fat Sesame Ginger Dressing', '80');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Onion Cheddar Burger', '310');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg & Cheese McGriddles', '450');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Quarter Pounder Burger with Cheese', '540');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Egg McMuffin', '300');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Chipotle BBQ Crispy Chicken Snack Wrap', '330');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Hotcakes, Egg Whites & Large Biscuit', '1060');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Side Salad, without dressing', '15');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Ranch Buttermilk Crispy Chicken Snack Wrap', '380');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Egg Whites & Large Biscuit', '730');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Creamy Caesar Dressing', '190');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Ranch Crispy Chicken Snack Wrap', '360');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McRib Burger', '500');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Double Quarter Pounder Burger with Cheese', '780');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Ranch Dressing', '200');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hotcake Syrup', '180');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Mozzarella Sticks', '200');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Regular Biscuit', '740');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Tartar Sauce', '140');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Iced Tea', '0');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Strawberry & Creme Pie', '310');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Ranch Salad, without chicken or dressing', '190');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Hotcakes, Egg Whites & Regular Biscuit', '970');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Butter Garlic Croutons', '60');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Chicken & Bacon McWrap', '500');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Double Cheeseburger', '440');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Fruit & Maple Oatmeal with Brown Sugar', '290');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Crispy Chicken Deluxe Sandwich', '530');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Ranch Salad with Crispy Chicken, without dressing', '450');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Spicy Buffalo Sauce', '35');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Steak, Egg & Cheese Bagel', '660');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Caesar Salad, with Crispy Chicken, without dressing', '350');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Crispy Chicken Ranch BLT Sandwich', '589');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Buttermilk Crispy Chicken Sweet Chili McWrap', '590');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Steak & Egg Biscuit, regular', '530');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry, with M&M's Candies, large', '929');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hot Habanero Sauce', '80');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Creamy Ranch Sauce', '110');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Holiday Mint McFlurry, snack size', '380');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Peanuts for Sundaes', '45');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Coffee Cream', '20');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Baked Hot Apple Pie', '250');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hot Mustard Sauce', '60');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Chicken Sweet Chili McWrap', '400');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Chicken & Ranch McWrap', '470');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg Whites & Cheese McGriddles', '410');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Mighty Wings, without sauce', '96');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage & Egg Whites Biscuit, regular', '470');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sweet 'N Sour Sauce', '50');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southwest Salad with Crispy Chicken, without dressing', '470');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage & Egg Biscuit, large', '600');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Clubhouse Crispy Chicken Sandwich', '750');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Large Biscuit', '810');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Fat-Free Chocolate Milk Jug', '130');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage McGriddles', '440');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Daily Double Burger', '440');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Whipped Margarine', '40');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Buttermilk Crispy Chicken Deluxe Sandwich', '580');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hotcakes & Sausage, without syrup or margarine', '510');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon & Cheese Quarter Pounder Burger', '599');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McDouble Burger', '390');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg Whites & Cheese Bagel', '530');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Pumpkin & Creme Pie', '270');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Ranch Grilled Chicken Snack Wrap', '290');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Chicken McNuggets, without sauce', '47');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Fried Cherry Pie', '230');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Steak, Egg & Cheese McMuffin', '430');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Reduced-Fat Vanilla Ice Cream Cone', '170');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Jalapeno Double Burger', '440');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Artisan Grilled Chicken Sandwich', '360');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Strawberry Preserves', '35');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Pralines & Cream McFlurry, regular', '679');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Spicy Chicken McBites', '270');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Mac Burger', '540');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Honey Mustard Grilled Chicken Snack Wrap', '250');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Filet-O-Fish Burger', '390');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Kiddie Reduced-Fat Vanilla Ice Cream Cone', '45');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage, Egg & Cheese McGriddles', '570');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg & Cheese Biscuit, large', '530');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Cheeseburger', '300');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Mac Snack Wrap', '330');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Chocolate Chip Cookie', '160');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage Biscuit, regular', '440');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry, with Oreo Cookies, large', '689');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage & Egg Whites Biscuit, large', '550');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Honey Mustard Crispy Chicken Snack Wrap', '330');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southern Style Chicken Biscuit, regular', '410');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry, with Reese's Peanut Butter Cup, large', '809');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Caesar Salad, with Grilled Chicken, without dressing', '190');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry with M&M's, regular', '650');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage & Egg Biscuit, regular', '520');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Chicken Bacon Clubhouse Sandwich', '610');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage Biscuit, large', '520');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Ranch Salad with Buttermilk Crispy Chicken, without dressing', '490');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('1% Low-Fat Milk Jug', '100');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Egg Whites & Regular Biscuit', '650');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage & Egg McMuffin', '470');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Crispy Chicken Club Sandwich', '669');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Honey', '50');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Buffalo Ranch McChicken Burger', '440');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage Burrito', '300');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Fruit & Maple Oatmeal, without brown sugar', '260');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Strawberry Sundae', '280');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage McMuffin', '400');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Crispy Chicken Classic Sandwich', '510');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Hotcakes & Large Biscuit', '1130');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Egg White Delight McMuffin', '250');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hotcakes, without syrup or margarine', '320');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Apple Slices', '15');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southwest Salad with Buttermilk Crispy Chicken, without dressing', '510');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Cuties', '40');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Chicken Classic Sandwich', '350');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hash Brown', '150');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southern Style Chicken Biscuit, large', '480');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southern Style Buttermilk Crispy Chicken Sandwich', '470');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grape Jam', '35');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry with Oreo Cookies, snack size', '340');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Buttermilk Crispy Chicken & Ranch McWrap', '660');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry, with Reese's Peanut Butter Cup, snack size', '410');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Cheddar McChicken Burger', '490');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Chipotle BBQ Grilled Chicken Snack Wrap', '250');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Chicken Selects Premium Breast Strips, without sauce', '123');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sweet Potato & Creme Pie', '290');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg & Cheese Bagel', '580');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Crispy Chicken Sweet Chili McWrap', '540');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sweet Chili Sauce', '50');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McChicken Burger', '370');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('BBQ Ranch Burger', '350');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Caesar Salad, without chicken or dressing', '90');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Ranch Salad with Grilled Chicken, without dressing', '310');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Chipotle Barbeque Sauce', '50');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southwest Salad with Grilled Chicken, without dressing', '330');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg Whites & Cheese Biscuit, regular', '400');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Fruit 'n Yogurt Parfait with Granola', '150');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Crispy Chicken & Ranch McWrap', '610');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Clubhouse Burger', '740');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Low-Fat Balsamic Vinaigrette', '35');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southwest Salad, without chicken or dressing', '160');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry with M&M's Candies, snack size', '430');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('French Fries', '116');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage, Egg Whites & Cheese McGriddles', '530');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hot Fudge Sundae', '330');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon Habanero Ranch Quarter Pounder Burger', '609');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Chicken Ranch BLT Sandwich', '440');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon McDouble Burger', '460');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sweet Tea', '88');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Creamy Southwest Dressing', '120');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('McFlurry with Oreo Cookies, regular', '520');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Sausage & Egg Whites McMuffin', '430');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Cinnamon Melts', '460');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Quarter Pounder Deluxe Burger', '600');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Tangy Barbeque Sauce', '50');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Ketchup', '10');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hamburger', '250');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Buttermilk Crispy Chicken & Bacon McWrap', '690');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Buffalo Ranch McChicken Burger', '370');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Big Breakfast with Hotcakes & Regular Biscuit', '1050');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg Whites & Cheese Biscuit, large', '480');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Grilled Chicken Club Sandwich', '510');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Buttermilk Crispy Chicken Bacon Clubhouse Sandwich', '790');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Hot Caramel Sundae', '340');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Oatmeal Raisin Cookie', '150');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Bacon, Egg & Cheese Biscuit, regular', '450');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Coffee, without milk or sugar', '0');
INSERT INTO `hwangmn`.`mcdonalds` (`food`, `calories`) VALUES ('Southwest Grilled Chicken McWrap', '510');
